mkdocs/build.py, mkdocs/themes/amelia/base.html, mkdocs/themes/bootstrap/base.html, mkdocs/themes/cerulean/base.html, mkdocs/themes/cosmo/base.html, mkdocs/themes/cyborg/base.html, mkdocs/themes/flatly/base.html, mkdocs/themes/journal/base.html, mkdocs/themes/mkdocs/base.html, mkdocs/themes/readable/base.html, mkdocs/themes/readthedocs/base.html, mkdocs/themes/simplex/base.html, mkdocs/themes/slate/base.html, mkdocs/themes/spacelab/base.html, mkdocs/themes/united/base.html, mkdocs/themes/yeti/base.html
If a page has a specific title, `page_title` will contain this and only
this. If the page has no title, or is the homepage, `page_title` will be
`None`. The `<title>` tag will always display at least the site name.
All of the themes' base.html files have been updated accordingly.
=> Page titles no longer contain the site name

docs/user-guide/configuration.md, docs/user-guide/styling-your-docs.md
I moved the custom theme discussion from the configuration page to the styling-your-docs page and expanded on it a little. Perhaps we should expand on the navbar and toc generation too. See #181.
=> First stab at custom theme documentation

mkdocs/build.py, mkdocs/test.py, mkdocs/toc.py
The [documentation for the toc extension](https://pythonhosted.org/Markdown/extensions/toc.html) states:
>If a marker is not found in the document, then the Table of Contents is available as an attribute of the Markdown class.
I refactored toc.py and build.py accordingly. Local tox testing showed newline differences in some tests due to my refactoring, I also adapted these tests.
A remaining issue is that test_copying_media errors out and I can't find the reason why. [Trace is here](https://gist.github.com/anonymous/db5dfa1b82fcc010c170).
=> removes TOC tag creation

mkdocs/nav.py, mkdocs/test.py
As discussed in https://github.com/rtfd/readthedocs.org/issues/1101, this makes directory links consistently have a trailing slash.
It looks like the fix for Python 2.6 in https://github.com/tomchristie/mkdocs/commit/f437ab058532851b369139e8ad261fbaee684448 could strip off `suffix` in addition to the additional `/` it was meant to remove - I've just switched the order so that `suffix` is appended after `rstrip('/')` is called.
I've also added a test (which failed without my fix).
=> Have slash at end of all page links

mkdocs/relative_path_ext.py
Previously, when pointing to a local url with params, for example:
a.php?a=x&b=y
I was getting something like:
a.php;a=x&b=y?a=x&b=y
Now I am able to get it correctly.
=> Solving issues with local url and params.

mkdocs/build.py
Without the continue, we build the previous page in it's place
Fixes #327
=> Continue when a markdown file can't be found

mkdocs/themes/readthedocs/css/theme_extra.css
I was also running into the issue referenced in #348.  This implements the fix that @cha0s suggested—it does indeed fix the problem.
=> Added padding to the bottom of index for the readthedocs theme

mkdocs/themes/readthedocs/base.html, mkdocs/themes/readthedocs/css/theme_extra.css
This keeps all our downstream theme tweaks in once place. Fixes #393
=> Move the inline CSS in ReadTheDocs to the theme_extra file

mkdocs/nav.py, mkdocs/tests/nav_tests.py
The current code was incorrectly processing titles for pages when an
explicit title was provided but the path to the file was nested in a
directory.
Fixes #392
=> Change the order of the Navigation processing to improve child_titles

mkdocs/themes/readthedocs/css/theme_extra.css
=> Wrap inline code samples otherwise they can become partly obscured

mkdocs/themes/readthedocs/css/theme_extra.css
Inherit the font weight and style to avoid code being made bold by
highlight.js and RTD CSS clashing.
Fixes #411
=> Remove italic and bold from some code highlighting in the RTD theme

mkdocs/themes/mkdocs/css/base.css
Images now display more as you would expect but can be broken up to
create the previous result by putting a blank image between them.
=> Display images inline in MkDocs theme

mkdocs/themes/amelia/js/base.js, mkdocs/themes/bootstrap/js/base.js, mkdocs/themes/cerulean/js/base.js, mkdocs/themes/cosmo/js/base.js, mkdocs/themes/cyborg/js/base.js, mkdocs/themes/flatly/js/base.js, mkdocs/themes/journal/js/base.js, mkdocs/themes/mkdocs/js/base.js, mkdocs/themes/readable/js/base.js, mkdocs/themes/simplex/js/base.js, mkdocs/themes/slate/js/base.js, mkdocs/themes/spacelab/js/base.js, mkdocs/themes/united/js/base.js, mkdocs/themes/yeti/js/base.js
After the changes in 4d9ad173, the offset in scrollspy is throwing the
position off and isn't needed.
=> Fixed issues with scrollspy

mkdocs/config.py, mkdocs/serve.py, requirements.txt, setup.py
Use python-livereload to automatically refresh your browser when changes are saved.
Closes #163
=> Automatically refresh the browser on edits

requirements.txt, setup.py
This should hopefully resolve #376 and a host of other issues fixed by Python-Markdown's newer releases.
=> Remove the upper limitation for Python-Markdown on Python >=2.7

mkdocs/build.py, mkdocs/config.py, mkdocs/new.py
By using io.open and explicitly defining the encoding on the call to
open every time, we should get consistant behavior across platforms
as open will not rely on each individual system's local settings
to determine what encoding to use. Note that io.open is an alias
to the built-in open function in Python 3. In Python 2.6+ it is a
Python 3 compatable implementation which works in Python 2. In the
future when all support for Python 2 is dropped, simply delete the
import statements with no additional changes to the code.
I expect this will fix both #239 and #352.
=> Fix cross-platform encoding issues.

docs/about/release-notes.md, mkdocs/build.py, mkdocs/compat.py, mkdocs/config.py, mkdocs/main.py, mkdocs/nav.py, mkdocs/relative_path_ext.py, mkdocs/serve.py, mkdocs/tests/nav_tests.py, mkdocs/toc.py, mkdocs/utils.py, requirements.txt, setup.py
This change aims to standardise path handling in MkDocs. Paths should
always be in the form expected by the current platform and then they
only need to be converted to URL's when used.
Fixes #439
=> Improve Path handling across MkDocs

docs/user-guide/configuration.md, mkdocs/build.py, mkdocs/tests/build_tests.py
I tried to keep the docs simple so non-python people would understand them
(I avoided calling the setting a 'dict,' etc.). Could probably use some
improvement.
All this extension mungling stuff should probably go in validate_config,
but that feels like an entireley differant issue than this, so I made the
changes inplace. Fixes #351
=> Add support for Markdown extension options.

mkdocs/build.py, mkdocs/config.py, mkdocs/tests/utils_tests.py, mkdocs/utils.py
Python Markdown inclusion order can be important when including various custom extensions.  Conflicts can arise as to where extensions get inserted in the workflow.  By preserving order of how extensions are
defined in the settings file, this can allow a user to control insertion order and work around these issues.  As Py26 supported is noted to be removed in the future, I saw no reason to add additional dependencies for OrderedDict.  Try catch statements can be removed when Py26 support is removed.
=> Preserve order of Python Markdown extensions

mkdocs/themes/mkdocs/base.html, mkdocs/themes/readthedocs/base.html
We only really need it on one place.
Fixes #489
=> Only include the build date and version on the homepage.

mkdocs.yml, mkdocs/build.py, mkdocs/config.py, mkdocs/nav.py, mkdocs/templates/sitemap.xml, mkdocs/utils.py
Add building extra templates
This is similar to extra_css and extra_javascript except it picks up
HTML and XML files and runs them through jinja2 with the global context.
This adds for quite a bit of flexability and allows people to easily add
custom site maps, static and templates htlp.
Fixes #28
Fixes #44
=> Add building extra templates

docs/index.md, docs/user-guide/configuration.md, docs/user-guide/writing-your-docs.md, mkdocs.yml, mkdocs/config.py, mkdocs/legacy.py, mkdocs/nav.py, mkdocs/tests/build_tests.py, mkdocs/tests/config_tests.py, mkdocs/tests/legacy_tests.py, mkdocs/tests/nav_tests.py, mkdocs/tests/search_tests.py, mkdocs/tests/utils_tests.py, mkdocs/themes/mkdocs/css/base.css, mkdocs/themes/mkdocs/nav-sub.html, mkdocs/themes/mkdocs/nav.html, mkdocs/themes/readthedocs/base.html, mkdocs/themes/readthedocs/css/theme_extra.css, mkdocs/themes/readthedocs/toc.html
The current pages configuration looks like this:
pages:
- ['index.md', 'Home']
- ['writing-your-docs.md', 'User Guide', 'Writing your docs']
- ['styling-your-docs.md', 'User Guide', 'Styling your docs']
- ['configuration.md', 'User Guide', 'Configuration']
- ['about/license.md', 'About', 'License']
- ['about/release-notes.md', 'About', 'Release Notes']
- ['about/contributing.md', 'About', 'Contributing']
This has a number of flaws:
- It isn't clear how to add second levels of navigation for
newcomers. This is often queried and not easy to document.
- We are representing a tree structure as a set of flat items
that need to be merged. This creates some interesting edge
cases, for example:
- ['writing-your-docs.md', 'User Guide']
- ['styling-your-docs.md', 'User Guide', 'Styling your docs'] …
=> Refactor the pages configuration

mkdocs/cli.py
Hi,
I use mkdocs with CMake and wanted to be able to give an output directory on the command line. This adds flexibility to the build process.
I added an `--outputdir` option to the `build` command. If not given, it behaves as it is now and compiles into the current directory.
Comments are welcome :)
=> Add a CLI option to output in a different directory

mkdocs/config/base.py, mkdocs/config/defaults.py, mkdocs/serve.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_tests.py
With a tuple we have a guaranteed order which makes the post validate
more predictable. Otherwise, if a post validate required the result of
another there was no way to do this. Now the prerequisties just need to
be higher in the config.
This change also renames the config option used internally to save the 
users config file.
=> Change the config schmea from a dict to a tuple

mkdocs/cli.py, mkdocs/serve.py
This removes duplicate config loading in the serve command and fixes an
issue where the reload wasn't working with changes on the config file.
=> Don't load the config outside the serve command

docs/user-guide/configuration.md, docs/user-guide/styling-your-docs.md, mkdocs/build.py, mkdocs/config/defaults.py, mkdocs/tests/build_tests.py
This change adds a new configuration option called `extra` which allows
uers to add an arbitrary set of data to the config that is passed to the
template context.
Fixes #144
=> Add `extra` config to support global template vars

mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_tests.py
I was making this change, to start warning users about #201. We don't have a concrete plan yet but the earlier we start warning them, the earlier we can start making the move.
I didn't get very far with it, because It causes this error, which almost makes sense except that it doesn't at all...
```
======================================================================
FAIL: test_extra_context (mkdocs.tests.build_tests.BuildTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/dougalmatthews/Code/python/mkdocs/mkdocs/tests/build_tests.py", line 359, in test_extra_context
self.assertEqual(config.validate(), ([], []))
AssertionError: Tuples differ: ([], [('theme', "The theme 'cosmo' will be remo[97 chars]s")]) != ([], []) …
```
=> This is a really confusing test failure, I can't figure out what is going wrong.

docs/user-guide/styling-your-docs.md, mkdocs/build.py, mkdocs/tests/build_tests.py, mkdocs/tests/integration.py
This update changes cf10026 so that templates must now access extra with {{ config.something }} rather than just {{ extra.something }}.
=> Expose the full config to templates rather than `extra` directly.

mkdocs/themes/mkdocs/js/base.js, mkdocs/themes/readthedocs/search.html
After clicking the `Search` link, the search input in modal should be 
autoselected for easier input.
> Due to how HTML5 defines its semantics, the autofocus HTML attribute has no effect in Bootstrap modals. To achieve the same effect, use some custom JavaScript:
```
$('#myModal').on('shown.bs.modal', function () {
$('#myInput').focus()
})
```
__Ref:__
http://getbootstrap.com/javascript/#modals
=> feat(theme/mkdocs): add autofocus for search input when modal opens

docs/user-guide/configuration.md, mkdocs/cli.py, mkdocs/config/defaults.py, mkdocs/gh_deploy.py
Adds an option of configuring the commit message to be set when using gh_deploy
=> Adding custom commit message option to gh_deploy

docs/user-guide/configuration.md, mkdocs.yml, mkdocs/build.py, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/utils_tests.py, mkdocs/utils.py
Config validation now handles all extension processing:
* Builtin extensions are defined and within the default scheme.
* User extensions are defined only as a list in the config. Note, this is
a backward incompatable change from the previous (short-lived) release.
* The users extensions are added to the list of builtins.
* Any duplicates are accounted for in validation.
* Extension options are supported by a child key/value pair on the ext name.
* All extension options are compiled into a format Markdown accepts
within the validation process and are saved to the internal `mdx_configs`
config setting.
* The `mdx_configs` setting is private and raises an error if set by the user.
* A whole suite of tests were added to test all aspects of ext validation.
All relevant build tests were …
=> Refactor Markdown Extension Options Config.

mkdocs/config/config_options.py, mkdocs/legacy.py, mkdocs/tests/config/config_options_tests.py
OrderedDict support was recently removed in #528, but there were still
some references to OrderedDict that are causing failures.  This
finishes the removal of OrderedDicts.
=> Finish removing OrderedDict code

mkdocs/tests/utils_tests.py, mkdocs/utils.py
This is based on the code in #495, but squashed and rebased and some changes removed.
Closes #495
Closes #494
=> Special case media being in the same directory as the markdown files

mkdocs/nav.py
Now that the page configuration can include multiple levels of headers and pages setting an item to active should recursively set all items in that tree to active.
=> Change to active status should recursively move up tree

mkdocs/themes/amelia/base.html, mkdocs/themes/bootstrap/base.html, mkdocs/themes/cerulean/base.html, mkdocs/themes/cosmo/base.html, mkdocs/themes/cyborg/base.html, mkdocs/themes/flatly/base.html, mkdocs/themes/journal/base.html, mkdocs/themes/readable/base.html, mkdocs/themes/simplex/base.html, mkdocs/themes/slate/base.html, mkdocs/themes/spacelab/base.html, mkdocs/themes/united/base.html, mkdocs/themes/yeti/base.html
This also includes a note that the documentation was built with MkDocs
This is related with a suggestion in #375
=> Add (centered) copyright footer Bootstrap and Bootswatch themes

mkdocs/cli.py, mkdocs/config/base.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_tests.py
Also ensure all debug messages are logged. And exit without
creating a new, unhelpful traceback by raising SystemExit.
Note that `sys.exit` raises SystemExit. However, by raising it
explicitly, we can also output a helpful explaination of why
the program exited. The program exists with an exit code of 1
to indicate is failed.
Fixes #536.
=> Ensure all errors and warnings are logged before exiting.

docs/about/release-notes.md, mkdocs/cli.py
* Added short options (`-a`) to most options.
* Added a `--quiet` option which silences INFO and WARNINGS.
* Made `--quiet` and `--verbose` common options to all subcommands (yet only defined once). For backward compat, they also work on the `mkdocs` parent command - although perhaps they should be removed from there. If you agree, let me know and I'll add that change to the PR.
=> CLI improvements

docs/about/release-notes.md, mkdocs/build.py, mkdocs/cli.py, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/exceptions.py, mkdocs/gh_deploy.py, mkdocs/legacy.py, mkdocs/nav.py, mkdocs/relative_path_ext.py, mkdocs/search.py, mkdocs/serve.py, mkdocs/tests/base.py, mkdocs/tests/build_tests.py, mkdocs/tests/cli_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_tests.py, mkdocs/tests/legacy_tests.py, mkdocs/tests/nav_tests.py, mkdocs/tests/new_tests.py, mkdocs/tests/search_tests.py, mkdocs/tests/toc_tests.py, mkdocs/tests/utils_tests.py, mkdocs/toc.py, mkdocs/utils.py, requirements/project.txt, setup.py
See #583
Locally, on Python 2 I'm getting two test failures (both exhibit same issue) with relative urls that I don't understand. I can't see how the changes I made would effect this. The weird thing is the tests pass in Python 3. If anyone has any suggestions, I'm happy to fix it.
Otherwise, everything should be good to go.
As I suspected, the parts of six that MkDocs was using was very minimal. Mostly `string_types` and one instance of `text_type` -- both of which are easy enough to replicate in `utils.py`. The rest is just a few different import paths, which is easy to deal with. I think six is way too much overhead/bloat for the amount of use MkDocs gets from it.
=> Removed six dependency.

docs/about/release-notes.md, mkdocs/assets/search/mkdocs/js/search.js
Including decoding of '+' to ' '.
Fixes #586.
=> Added URL decoding to `getSearchTerm()`

docs/about/release-notes.md, mkdocs/config/base.py, mkdocs/tests/legacy_tests.py, mkdocs/tests/utils_tests.py, mkdocs/utils.py
- All strings are redirected to be loaded as unicode
- I was experiencing an issue on my system where I was getting errors
trying to access config file objects because they were not being closed.
In all cases, once the YAML content was loaded, we were done accessing
the file content.  YAML object will close file access in the objects
once processing the content is complete.
=> YAML now loads all strings as unicode

docs/about/release-notes.md, mkdocs/cli.py
Only the error message is displayed for socket errors.
=> Cleaned up socket.error stack trace for mkdocs serve.

docs/user-guide/configuration.md, docs/user-guide/writing-your-docs.md
It now better reflects the new pages configuration format. The pages section
in `configuration.md` was also reduced to a summary, with most of the
details now in `writing-your-docs.md`. Also fixed a few typos.
=> Updated documentation on pages configuration.

docs/about/release-notes.md, mkdocs/tests/toc_tests.py, mkdocs/toc.py
I have noticed the ampersand in a header like this:
```
```
converted to `&amp;` by markdown, is dropped in the resulting TOC:
```
Tips  tricks
```
This patch fixes this by adding `handle_entityref` (and `handle_charref`, while we're at it) to `mkdocs.toc.TOCParser` which pass through such entities unchanged.
=> Handle (pass-through) character and entity references in TOC parser

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py
This is causing a number of users issues. So, this will now be a opt-in
feature only.
Fixes #616
=> Don't populate extra_templates by default

mkdocs/relative_path_ext.py, mkdocs/tests/build_tests.py
Markdown encodes autolink email addresses as per the rules. However,
urlparse does not properly parse the encoded scheme. Fixes #646.
=> Ignore autolink email addresses.

mkdocs/search.py, mkdocs/tests/search_tests.py
Currently search index generation is limited to H1 and H2, which is hard-coded. I have found it necessary to extend this to H3 and H4, as I wanted to provide more specific search results. Not sure what a good balance would be (e.g. stop at H4), as the level of headings included in the TOC, for example, is up to the template, so I opted for no limits.
=> Generate search index entries for all headings, not just H1 and H2

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_tests.py
Both files and directories should be sorted to ensure consistent ordering of
pages in the menus across builds and systems. Turns out to be a simple fix.
As `os.walk` provides a reference to the list of dirs it uses internally,
we can modify that list in place and it will use the modified list.
While this may not give proper alphanumeric ordering for all languages,
it goes ensure consistent ordering. For more control over ordering,
it is expected that a plugin could be used once that API becomes available.
This fixes #638.
=> Ensure consistent order of auto-populated pages.

mkdocs/build.py
Minor clean up that looks like it doesn't functionally affect anything.
Any reason we can't do this?
=> Remove `build_sitemap()` function.

mkdocs/__main__.py, mkdocs/tests/cli_tests.py, setup.py
This uses the standard entrypoint name and allows `python -m mkdocs` to
work.
=> Rename cli.py to __main__.py

mkdocs/__main__.py
=> Disable the warning for unicode_literals in Click and Python 2

CONTRIBUTING.md, docs/about/contributing.md, docs/about/license.md, docs/about/release-notes.md, docs/index.md, docs/user-guide/configuration.md, docs/user-guide/custom-themes.md, docs/user-guide/deploying-your-docs.md, docs/user-guide/styling-your-docs.md, docs/user-guide/writing-your-docs.md, tox.ini
Also added README.md and CONTRIBUTING.md to the linter.
Note, that I am still getting one failer (in two locations). However
I consider that failer a bug in the linter and have reported it
upstream. We could disable that Rule (MD031), but as we are not
requiring the lint rules to pass presently, I just left it alone.
Also, while the code linter is set to allow lines 119 chars long,
I am using the Markdown linter's default of 80. Prose is easier to
read with shorter line lenghts, so I think it makes more sense to
use the default. Also, changing the default would have required
adding a config file. Adding a Ruby file for only one minor setting
seems silly, so I left it alone.
=> Corrected lint errors in Markdown docs.

mkdocs/themes/readthedocs/base.html
readthedocs.org needs the file name in order to identify the correct source file to link to the same file in other versions of the same documentation or to the source on GitHub.
See rtfd/readthedocs.org#1480 for more information.
=> Provide the source file name to the JS in readthedocs theme

.travis.yml, appveyor.yml, mkdocs/search.py, mkdocs/tests/search_tests.py, mkdocs/toc.py, tox.ini
Also include a fix for one failing test with HTMLParser. Three additional
tests are still failing for a different problem related to search.
If I work out that issue, I'll push up another commit to fix it here.
=> Add support for Python 3.5

docs/index.md
As of 40dc17e17e5, any mention of the `--help` flag had been removed from
the documentation. A breif summary has been added here. However, the output
of `--help` has not been included as that can change in the future and
updating the docs every time a option is updated become unnesecarily
duplicative (as the command line is self-documenting). This fixes #767.
=> Document the `--help` flag.

mkdocs/themes/readthedocs/css/theme_extra.css
The RTD CSS uses both the `html` and `p` selectors to define font size.
MkDocs used to use `body` to reduce size, which only applied to anything
else than `p`. This patch restores compatibility with RTD by using html,
not body. Fixes #801.
=> readthedocs theme: Keep same font-size everywhere

mkdocs/config/config_options.py
I'm currently getting `<loc>None/</loc>` in my sitemap, see http://help.tutorcruncher.com/sitemap.xml
I believe this should fix it however we should probably add a test, where would be the best place for the test to go?
I can see that the real solution is to set `site_url`, either mkdocs should deal better with no `site_url` or it should be required.
=> correct site_url in sitemap

docs/user-guide/styling-your-docs.md
I also improved readability and reduced confusing repetition of the word "theme" here.
=> It had Bootstrap instead of Bootswatch in documentation

docs/about/license.md, docs/about/release-notes.md, docs/index.md, docs/user-guide/custom-themes.md, docs/user-guide/styling-your-docs.md, mkdocs/config/config_options.py, mkdocs/tests/utils/utils_tests.py, requirements/project-min.txt, requirements/project.txt, setup.py
This change removes the dependency on mkdocs-bootstrap and mkdocs-bootswatch.
It also updates all references in the code. The only remaining connection is
when a user specifies one of these themes but they are not installed they get
slightly helpful error.
=> Remove external themes from MkDocs

mkdocs/themes/readthedocs/css/theme_extra.css
If you do a side-by-side comparison of [docs.readthedocs.org](https://docs.readthedocs.org/en/latest/builds.html#mkdocs) you can see that mkdocs font is smaller and the colors are different for headers (mkdocs uses blue and readthedocs uses black).
This removes those two discrepancies.
=> Remove font-size in readthedocs/theme_extra.css

mkdocs/themes/mkdocs/css/highlight.css, mkdocs/themes/readthedocs/css/highlight.css, mkdocs/themes/readthedocs/css/theme_extra.css
Here are "after" screenshots (you can see the "before" in #855):
MkDocs
ReadTheDocs
One important note: this effectively reduces the padding in the MkDocs theme for code blocks, since I eliminated the double-padding. If you prefer the level of padding that it has now (I don't), I can add some more padding to *all* the code blocks so that it looks like it does currently, but is the same whether it's highlighted or not.
=> Fix display of code blocks with `nohighlight`; resolves #855

mkdocs/utils/__init__.py
=> fixes https://github.com/mkdocs/mkdocs/issues/728

mkdocs/themes/readthedocs/search.html
The search tool will replace the text with "No results found" if that is the case.
No reason to display is here. Also, the default text displays when the search 
is running (especially if the search takes a long time), so it might as well be 
accurate and indicate that the search is running. Addresses #859.
=> Update default text when search is running.

mkdocs/themes/readthedocs/css/theme_extra.css
This matches readthedocs.org much better since there was previously 0 padding top/bottom for <code>variable</code>.
See this page for a comparison: https://docs.readthedocs.org/en/latest/i18n.html
=> Add a bit more padding to inline `code`

mkdocs/commands/build.py, mkdocs/tests/build_tests.py, mkdocs/utils/__init__.py
Fixes #807. Used the fnmatch lib which supports Unix shell-style wildcard patterns (not regex). This allows patterns like `'*.py'`, `'.*'`, etc. A list of excluded patterns are passed to `mkdocs.utils.copy_media_files`. The pattern `'.*'` is included by default and not overridable.
=> Ensure various template files are not copied with media files.

mkdocs/config/base.py, mkdocs/tests/config/base_tests.py
Refactored fix supplied in #735 and added tests.
=> Support loading closed config file descriptor.

tox.ini
We seem to get getting some Linkchecker failures in #921
=> Limit requests version for LinkChecker

codecov.yml
CodeCov now requires that we customise it with a config file (ala Travis and
AppVeyor.). This is just the default config.
=> Add a config file for CodeCov

docs/about/release-notes.md, docs/user-guide/custom-themes.md, mkdocs/commands/build.py, mkdocs/nav.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/mkdocs/content.html, mkdocs/themes/mkdocs/nav.html, mkdocs/themes/mkdocs/toc.html, mkdocs/themes/readthedocs/base.html, mkdocs/themes/readthedocs/breadcrumbs.html, mkdocs/themes/readthedocs/footer.html, mkdocs/themes/readthedocs/toc.html, mkdocs/themes/readthedocs/versions.html
A deprecation warning is issued for all old variables and all new
page specific variables are attributes of the 'page' object.
Global variables are uneffected, except page_description.
See the changes described in the release notes for details.
Fixes #874.
=> Refactor page specific template variables.

mkdocs/tests/config/config_options_tests.py
I think this will resolve the issue. Not able to test conclusively locally as I refuse to use deb packages for Python libs. @brianmay, can you confirm this solves the problem raised in #923?
=> Ensure tests use actual package location. Fixes #923.

docs/about/release-notes.md, mkdocs/commands/build.py
=> Support SOURCE_DATE_EPOCH environment variable for "reproducible" builds.

docs/user-guide/deploying-your-docs.md
scp -r ./site command was missing the E in user.
=> Fix typo in scp command

docs/about/release-notes.md, docs/user-guide/custom-themes.md, docs/user-guide/styling-your-docs.md, mkdocs/commands/build.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/mkdocs/main.html, mkdocs/themes/mkdocs/nav-sub.html, mkdocs/themes/mkdocs/nav.html, mkdocs/themes/mkdocs/search.html, mkdocs/themes/mkdocs/toc.html, mkdocs/themes/readthedocs/base.html, mkdocs/themes/readthedocs/breadcrumbs.html, mkdocs/themes/readthedocs/footer.html, mkdocs/themes/readthedocs/main.html
Partially addresses #607.
Note that we have to rename `base.html` to `main.html` and then create a new `base.html` which is an empty file that "extends" `main.html `. We could reverse the roles of those two files, but that would be backward incompatible with existing custom/third party themes as all themes are loaded from `base.html`. Existing custom themes may not have a `main.html` and switching the role of the two files, despite being more sensible,  could break existing custom and third party themes. Of course, if we want to make the backward incompatible change, now is the time to do it. Let me know and I'll update this PR.
Also note that this provides a way for users to override the behavior of next/prev links when `include_next_prev` is deprecated (see #633, #679,  #681, & #946), …
=> Support theme customization with blocks

mkdocs/commands/gh_deploy.py, mkdocs/tests/gh_deploy_tests.py, mkdocs/tests/utils/ghp_import_tests.py, mkdocs/utils/ghp_import.py
Ran into this thinking my CI server had deployed properly, but it hadn't because of an authentication issue. However, the process returned a success code and the logs indicated success.
Fixes #966 
One note is that this doesn't raise on error. Happy to update if you'd like to have this raise an exception in addition to logging the error.
=> Error on failure to git push as part of gh-deploy

docs/user-guide/configuration.md, docs/user-guide/custom-themes.md, mkdocs/commands/build.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/nav.py, mkdocs/tests/config/config_options_tests.py, mkdocs/themes/mkdocs/nav.html, mkdocs/themes/readthedocs/breadcrumbs.html
This patch adds support for a configuration option `edit_uri` that is used to generate a link directly to an individual page in the source repository.
Fixes #269
=> Direct "Edit on ..." links to individual pages

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
Rather than the view-based `blob` URL, default to the `edit` URL for GitHub-hosted repositories. Also update the release notes.
See #975 for previous work and the discussion leading to this change.
=> Use the edit url for the 'Edit on...' links

mkdocs/themes/mkdocs/nav.html
Unlike the readthedocs theme, the wording isn't "edit on .." or
similar. Taking users to the edit page is therefore confusing.
Fixes #269
=> Link to the repo from the MkDocs theme

docs/user-guide/styling-your-docs.md
theme_dir is listed twice at the bottom links, this removed the
one that relates to this page. All usages make sense when linking
directly to the config page.
=> Remove extra theme_dir alias

mkdocs/themes/readthedocs/css/theme_extra.css
I think this offers the best compromise. This is based on my
testing of the suggestion @facelessuser made.
Fixes #709
=> Add white-space: pre-wrap to code in the readthedocs theme

docs/about/release-notes.md, docs/user-guide/deploying-your-docs.md, mkdocs/__main__.py, mkdocs/commands/build.py, mkdocs/commands/serve.py, mkdocs/utils/__init__.py
This provides a --dirty-reload option to the serve command. It simply operates by comparing the modified time of the markdown and html. This is a much simpler solution to what was proposed in 
#971 and is meeting my needs well.
Note, that there was some discussion of --clean/--no-clean with the serve command. However, passing a --clean/--no-clean option to the serve command doesn't do anything since each time it runs is creates a different tmp directory (at least for me). So, effectively it is always clean. 
(closes #990)
=> A simple method for providing a quick/dirty reload option (refs #990)

docs/about/release-notes.md, mkdocs/__main__.py, mkdocs/tests/cli_tests.py
Fixes #738 
This probably still needs a test or two. I just ran out of time. I'll get to it later.
=> Don't override config value for strict mode if not specified on CLI.

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/config/config_tests.py
Raise an error when site_dir is in docs_dir (as opposed to a warning)
and raise an error when docs_dir is the parent dir of the config file.
Fixes #610 and #972.
=> Enforce stricter docs_dir validation.

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs.yml, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/config/config_tests.py
This completes the work started in #988 (I've included that commit).
I did not specifically add a test to verify that a warning is being issued as the next release will just remove it anyway. However, if you would like to test it, just remove the `extra_css` [entry][1] from the `mkdocs.yml` file and build MkDoc's documentation and the warning will be issued.
This fixes #986 and closed #988.
[1]: https://github.com/waylan/mkdocs/blob/8ab812a079e5f03bdca496514e22fa710a7c7f07/mkdocs.yml#L21
=> Deprecate auto-populating extra_css/javascript

docs/user-guide/styling-your-docs.md, mkdocs/themes/mkdocs/base.html, mkdocs/themes/readthedocs/base.html
Some scripts need to execute after the page has finished loading.
To ensure that, the `scripts` block is placed at the bottom of the page.
However, if a user embeds scrpts within the body, and those scripts
rely in libs, then the libs need to already be loaded. By having
`libs` be a seperate block at the top of the page (int he header),
we can ensure that will work.
And we still want the libs in a block so a user can override them,
or even add to them (via `{{ super() }}`).
Fixes #956
=> Break up libs and scripts into 2 separate template blocks.

docs/about/release-notes.md, mkdocs/__main__.py, mkdocs/commands/gh_deploy.py, mkdocs/tests/cli_tests.py, mkdocs/utils/ghp_import.py
This replicates the recent addition to the ghp_import.py tool (see
https://github.com/davisp/ghp-import/commit/49cfe6e6).
The default is to not force, but if needed (perhaps when deploying
from a CI server), the --force flag can be included.
Fixes #973.
=> Add --force flag to gh-deploy command.

mkdocs/themes/readthedocs/css/theme_extra.css
It's hard to explain why the alignment looks bad so I will show you a before and after screenshots.
This looks fine and will remain the same :+1: 
This looks wrong because the sub-menu item moved to the left after being clicked :open_mouth: 
Here we can see that the menu item is properly aligned when it is selected :tada:
=> Better alignment for current selected menu item in readthedocs theme

docs/index.md
Remove chocolately recommendation, which was never any good for Python.
Closes #1025.
=> Improve installation instructions.

mkdocs/commands/gh_deploy.py
- Add missing trailing / when printing out GitHub URL. Without the trailing `/` a GitHub error message is shown
- Switched from `http` to `https`, since it's now enabled by default by GitHub
=> Update github.io URL

docs/about/release-notes.md, docs/user-guide/configuration.md, docs/user-guide/custom-themes.md, mkdocs/themes/mkdocs/css/base.css, mkdocs/themes/readthedocs/css/theme_extra.css
A better fix for #834. Also see discussions on PRs #1027 and #1034, of which this is a replacement.
This was tested with [this gist][1] as a sample test page.
[1]: https://gist.github.com/waylan/f5503feb9177ffc3aa790561d8220598
That page renders like this in the `readthedocs` theme:
And like this in the `mkdocs` theme:
=> Account for wide tables and wrap inline code spans.

docs/about/release-notes.md, mkdocs/commands/build.py, mkdocs/nav.py, mkdocs/tests/nav_tests.py
An error page can be served from any location and therefore it is
impossable to pre-build an error page with correct relative URLs.
With absolute URLs, the error pages will properly link to other
pages in the nav as well as media files (css, js, images, etc) from
the template regardless of the actual URL the file is served from.
However, to continue to support environments where the docs root is a subdir
of the server root, all other pages must continue to use relative URLs.
The `site_url` is used to determine the server root when building
absolute URLs for the error page to ensure those URLs continue to work
in that type of environment.
Relative URLs are also nessecary for those who browse the site on the
local file system (via `file://`). In that case, the error page will be
broken. …
=> Use absolute URLs in nav & media links from error templates.

docs/about/release-notes.md, docs/index.md, docs/user-guide/configuration.md, docs/user-guide/custom-themes.md, mkdocs/commands/build.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/nav.py, mkdocs/templates/sitemap.xml, mkdocs/tests/integration/complicated_config/mkdocs.yml, mkdocs/themes/mkdocs/base.html, mkdocs/themes/mkdocs/nav.html, mkdocs/themes/readthedocs/base.html, mkdocs/themes/readthedocs/breadcrumbs.html, mkdocs/themes/readthedocs/footer.html, mkdocs/themes/readthedocs/versions.html
This is a continuation of the work started in #921. That PR addressed the page context. This addresses the global context (see #874 for more info).
Still a lot of work to do on this. I started by rebasing #681 and gracefully deprecating `include_nav` and `include_next_previous` rather than removing them. I've left the individual commits for now so you can compare my changes to the original.
=> Global Template vars refactor

mkdocs/__main__.py, mkdocs/commands/serve.py
Also removed the short option `-d` from the `--dirtyreload` flag to match
the other options. Fixes #1074
=> Consistently use "dirty" to indicate dirtyreload server.

MANIFEST.in
I believe this typo is preventing the license from being included in the PyPI tarballs.
=> fix name of license file in manifest

mkdocs/__main__.py, mkdocs/commands/build.py, mkdocs/tests/integration.py
Newly released Flake8 version 3.2.0 resulted in a few previously missed
[errors being reported][1] for the first time. First observed in #1091.
[1]: https://travis-ci.org/mkdocs/mkdocs/jobs/175856685#L224
=> Flake8 Cleanup.

docs/index.md
I created a [MkDocs Chocolatey Package](https://chocolatey.org/packages/mkdocs). Therefore this PR, to mention Chocolatey as supported package manager.
=> Add chocolatey to list of supported package managers

.travis.yml
It seems that the pypy3 version is old and pip no longer supports it. We can maybe remove this entirely, but for now lets keep it but turn the build green again.
=> Allow pypy3 failures for now

docs/user-guide/configuration.md
See: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/defaults.py#L119
=> Correct the default for the remote_name config

mkdocs/config/config_options.py, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
Previously, all installed themes were "loaded" each time the CLI
was run. Now, only the names are obtained unless the user explicitly
requests a theme by name (in user config for via command line option).
A broken third party theme can no longer "break" a project in which
is is not being used.
Fixes #1104.
=> Only "load" a theme when it is explicitly requested by the user.

requirements/project-min.txt, requirements/project.txt, setup.py
This ensures older pyinotify versions don't break the livereload server.
Fixes #1106.
=> Up livereload version to >=2.5.1.

mkdocs/commands/build.py, mkdocs/nav.py, mkdocs/tests/nav_tests.py, mkdocs/utils/__init__.py
Also maintain pattern of ending urls with a slash in nav (all non-error pages
do so the error page shoudl also). A couple extra checks to ensure base_url
doesn't end in a slash though as it is expected that the string appended
to base_url will always begin with the slash.
Fixes #1131
=> Ensure nav.homepage.url is not blank on error pages.

mkdocs/themes/readthedocs/base.html, mkdocs/themes/readthedocs/nav.html, mkdocs/themes/readthedocs/toc.html
* Fix a nested `<li>` bug.
* More closely replicate nesting of the Sphinx theme nav (related to #588).
* If sections headers ever get urls, this will support them (related to #73).
I pulled the RTD changes out of #1042 and applied them separately with a few tweaks. These changes need to happen regardless of whether #1042 get rejected (my current leaning) and this gets us closer to resolving #588. The remaining work to complete #588 should be CSS/JS related only.
I should note that this is not an exact clone of the upstream (Sphinx)  theme (although it is closer). In the upstream theme, there is only provision for one level of section headings and one level of pages were we allow pages in the section heading level and multiple levels of pages under a section. If we were to take it that …
=> Refactor readthedocs navigation template.

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
As neither setting can point at a child dir of the other, `/` would be an
invalid value for either setting. However, given its unique nature,
`os.path.abspath` does not follow normal behavior of returning a string without
an ending slash when passed `/`. Therefore, we need to special case it.
Fixes #1161.
=> System root ("/") is not a valid path for site_dir or docs_dir.

.travis.yml, docs/about/release-notes.md, docs/index.md, mkdocs/relative_path_ext.py, setup.py, tox.ini
MkDocs most likley will no longer run on Python 2.6. All relevant tests
have been removed. Closes #165.
=> Drop support for Python 2.6.

docs/about/release-notes.md, mkdocs/__main__.py, mkdocs/commands/build.py, mkdocs/tests/cli_tests.py
=> Remove previously deprecated `json` command.

mkdocs/commands/serve.py
Live reload (with `mkdocs serve`) is broken in 0.16.2; saving a file triggers a reload, but the page contents doesn't change because the server returns a 304 Not Modified.
I did a bit of testing, and it looks like efbc78922dc379cecc95beef8d7e1badc49959a2 (#1141) is the suspect commit. The `_get_handler` method introduced in that PR inherits from `tornado.web.StaticFileHandler`. livereload has a slightly customized `StaticFileHandler` which disables 304's: https://github.com/lepture/python-livereload/blob/master/livereload/handlers.py#L151-L153
This fixes the issue by using the correct `StaticFileHandler`
=> Fix live reload

docs/about/release-notes.md, mkdocs/commands/build.py, mkdocs/config/defaults.py, mkdocs/nav.py, mkdocs/search.py, mkdocs/tests/base.py, mkdocs/tests/build_tests.py, mkdocs/tests/nav_tests.py, mkdocs/tests/search_tests.py, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py, mkdocs/utils/meta.py
All Markdown handling is now contained within the `Page` object, which
external code no longer needs to know the internals of.
A slightly different approach to the work started in #713.
Include the multimarkdown meta-data parser from docdata
See: https://github.com/waylan/docdata
Tests have been updated. However, as noted in #713, they could use
some refactoring. The existing tests all pass. We can leave refactoring
as a separate matter from this.
Closes #713.
=> Refactor Markdown handling.

docs/about/release-notes.md
Once we fix #1177, then we'll release 0.16.3. Between that and the fix in #1174 we have 2 regressions which are breaking things for users and need to be fixed ASAP.
=> Start release notes for 0.16.3

mkdocs/themes/readthedocs/js/theme.js
Fixes a JavaScript error when looking for a current page in the TOC when there is not a current page selected, in the case of Search, 404 or any page that isn’t listed in the TOC. This checks if a TOC item with the class of ‘current’ is in the document, and if not, does not call the viewport check or scroll the TOC area.
=> ReadtheDocs theme TOC scroll bug

mkdocs/config/config_options.py
Minor typo fix to separate the URL from the rest of the warning message in
> ERROR   -  Config value: 'theme'. Error: The theme 'simplex' is no longer included in MkDocs by default and must be installed with pip. See http://www.mkdocs.org/about/release-notes/#add-support-for-installable-themesfor more details
=> Insert whitespace after url

mkdocs.yml
The current link is broken. I've reverted it to its previous state.
=> fix the link to Tom Christie in the copyright notice

MANIFEST.in, docs/about/release-notes.md, docs/css/extra.css, docs/user-guide/configuration.md, docs/user-guide/custom-themes.md, docs/user-guide/styling-your-docs.md, mkdocs/commands/build.py, mkdocs/commands/serve.py, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/config/config_tests.py, mkdocs/tests/integration/complicated_config/mkdocs.yml, mkdocs/tests/theme_tests.py, mkdocs/theme.py, mkdocs/themes/mkdocs/mkdocs_theme.yml, mkdocs/themes/readthedocs/mkdocs_theme.yml, mkdocs/utils/__init__.py
Themes now have `theme` objects, and theme specific configs.
Themes can inherit from other themes. Users (and theme authors)
can define custom static templates and variables.
Note that the `theme_dir` config option is being deprecated in favor of a nested `custom_dir` option.
This fixes #1164.
=> Theme refactor

mkdocs/tests/config/config_tests.py, mkdocs/themes/readthedocs/404.html, mkdocs/themes/readthedocs/mkdocs_theme.yml
Replaces #1178 since we've refactored the theme loading code (see #1201).
=> Add 404 page for RTD Theme

docs/user-guide/configuration.md, mkdocs/nav.py, mkdocs/tests/nav_tests.py
Fixing #1220
Includes tests and documentation.
=> Adding support for query strings in the edit_uri

mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
We are working in a team with both MacOS and Windows computers. We where facing and estrange issue where media routes where not properly generated in Windows.
If you have the following folder structure:
- mkdocs.yml
- docs
- level1
-  level2
- img
- sample.png
- index.md
Where the content of index.md is:
```markdown
This is a route test:
``` 
The output in MacOS is referencing the current path (right):
```html
<p> 
This is a test
</p>
```
However, in Windows we where getting a reference to the upper folder (wrong):
```html
<p> 
This is a test
</p>
```
After some debugging in both Windows and MacOS platforms, I found that the following hack where causing this behaviour:
```python
def create_relative_media_url(nav, url):
...
if (nav.file_context.current_file.endswith("/index.md") is False …
```
=> Removed hack that broke images on Windows

mkdocs/utils/__init__.py
Without the with construct, jython does not close the underlying file handler properly and the result is an empty file.
=> Close file properly after writing.

.travis.yml
Travis-CI no longer installs all supported Python versions by default. We need to define the Python version(s) we want in the `python` config setting to ensure that that version is installed before running the tests. Therefore, we need a matrix of `python` and `env` settings to ensure the proper Python versions are matched up with their corresponding tox environments.
=> Refactor .travis.yml to use matrix.

.travis.yml
Travis-CI no longer installs all supported Python versions by default. We
need to define the Python version(s) we want in the `python` config setting
to ensure that that version is installed before running the tests.
Therefore, we need a matrix of `python` and `env` settings to ensure the
proper Python versions are matched up with their corresponding tox
environments. We can also isolate dependencies to specific envs.
=> Refactor .travis.yml to use matrix on 1.0-dev.

mkdocs/config/__init__.py, mkdocs/config/config_options.py, mkdocs/nav.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/nav_tests.py
i encountered this tailed traceback:
```
File "/home/user/mkdocs/mkdocs/nav.py", line 180, in __init__
self._set_edit_url(config['repo_url'], config['edit_uri'])
File "/home/user/mkdocs/mkdocs/nav.py", line 263, in _set_edit_url
if not edit_uri.startswith('?') and not edit_uri.startswith('#'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
=> Fixes a bug when 'edit_url' is not defined in the config

docs/user-guide/plugins.md, mkdocs/commands/build.py, mkdocs/nav.py, mkdocs/plugins.py, mkdocs/tests/build_tests.py, mkdocs/tests/search_tests.py
This allows to override the loading of source files, e.g. to fetch it from a remote location or for generated contents.
=> Adds 'load_markdown' event

appveyor.yml
Addresses problem discovered in #1290.
=> get_pip.py installs setuptools. ez_setup.py is deprecated.

mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
In various stages of a build, a new file may overwrite a previously written
file (for example to override a theme). If a source file is read-only, the
copied file cannot remain read-only. Therefore, permissions must not be
copied with a file. `shutil.copyfile` only copies a file's contents and is
now being used to copy all files.
Fixes #1292.
=> Do not copy permissions with files.

mkdocs/config/config_options.py, mkdocs/config/defaults.py
Hello,
In our company (OVYA), all projects have their own documentation and we want to assemble then in a general documentation via "git sub modules".
In each documentation we set docs_dir=content and, in the general documentation, we place all the sub modules in the directory docs.
In creating a symlink (unix system) from docs/PROJECT_NAME/content to content/projects/PROJECT_NAME we will expect to have all the documentation in one place.
Unfortunately, Mkdocs does not follows the symlinks that we created…
This pull request add a new option that allows to follow directories links.
=> Add option follow_links controling the docs_dir walker to follow directories links

docs/about/release-notes.md, docs/user-guide/configuration.md, docs/user-guide/plugins.md, mkdocs.yml, mkdocs/config/defaults.py, mkdocs/tests/plugin_tests.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/mkdocs/nav.html, mkdocs/themes/readthedocs/base.html, setup.py
Maintains better backward-compatability. Documentation updated, including
how to override the default. Also renamed the entry_point to 'search'.
The lib is still 'legacy_search'. When a new/better search plugin is
developed, the `search` entry_point will be pointed there so the default
behavior will inlcude the upgrade and a new `entry_point` will be added
('legacy_search') which points to the old plugin for those who really want
it.
=> Set 'search' as a default plugin.

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/tests/nav_tests.py
This partially reverts commit f90c44a20d12635db83021ebd11c31bbac4e28d3.
The behavior is still deprecated, but a warning is now issued to inform
the user that the "extra" files not listed have been ignored.
=> Partially Revert "Remove deprecated autofill of extra configs."

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/themes/mkdocs/nav.html
Theme shows either a repo link or an edit link depending on whether
`edit_uri` is set. Also clarified documentation that this behavior is
dependent upon theme support. Fixes #1129.
Updates #1304 with documentation and release notes.
=> Add "edit link" support to MkDocs theme.

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/commands/serve.py
When serving locally, the `site_url` actually is the `dev_addr`, so the
config should relfect that. Note that this override must happen after
config validation so that the proper defaults are evaluated for the
`dev_addr` setting. It cannot happen as part of "post_validation" as
there is no way to know the dev server is running within the config
validation (for example, the dev_addr may not be None as the user could
have set the `dev_addr` setting in their config file). Overriding it
from the serve command is the least invasive method and guarantees it
only happens when the local dev server is being run.
Also cleaned up `dev_addr` docs, which were missleading in some respects
and actually encouraged using the dev server over a network.
Fixes #1317. 404 Error pages now work on the loval dev …
=> Override site_url with dev_addr on local server.

docs/about/release-notes.md, docs/user-guide/configuration.md, docs/user-guide/custom-themes.md, mkdocs/contrib/legacy_search/__init__.py, mkdocs/tests/config/config_tests.py, mkdocs/tests/theme_tests.py, mkdocs/themes/mkdocs/mkdocs_theme.yml, mkdocs/themes/readthedocs/mkdocs_theme.yml
Added theme customization settings to the search plugin:
* include_search_page: Determines whether the search plugin expects the
theme to provide a dedicated search page via a template located at
`search/search.html`.
* search_index_only: Determines whether the search plugin should only
generate a search index or a complete search solution.
Themes should define these settings in their `mkdocs_theme.yml` config file.
Documentation has been updated as well. Fixes #1315.
Note: while we would not normally add new settings (features) in a point
(bugfix) release, this is fixing a regression for third party themes.
Therefore, it is a "bugfix" and appropriate for a point release.
=> Fix search for third-party themes.

docs/about/release-notes.md, mkdocs/toc.py
This could be useful in templates. Fixes #1325.
=> Add length support to toc.

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/nav_tests.py
Also broke up `edit_uri` tests into individual methods and added a few
missing senarious. Fixes #1321.
=> Support `repo_url` with missing ending slash.

docs/about/release-notes.md, mkdocs/config/config_options.py
The warning for missing files should only be issued if the config
setting is empty. The warning only exists because we disabled
autopopulating of the settings. Autopopulating only used to run
when the setting was empty so the warning is not nessecary if
the setting has been populated.
Given the above, no string comparisons need to be made as we
only need to check if any files exist when empty. Therefore, we
don't actually need to normalize paths. As we are no longer
modifying users' strings, they can again put any string in their
config, such as URLs of CDNs.
Fixes #1335 & #1336.
=> Correct `extra_*` config setting regressions.

docs/user-guide/configuration.md, docs/user-guide/deploying-your-docs.md
PyPI's documentation hosting has been deprecated, and in fact, it
is no longer possable to upload documentation to PyPI. Therefore,
it is a disservice to our users to document how to deploy to that
service.
See the mailing list dicussions for the official announcement:
https://mail.python.org/pipermail/distutils-sig/2015-May/026327.html
https://mail.python.org/pipermail/distutils-sig/2015-May/026381.html
As a result of that, Python-Markdown has moved its documentation to
https://python-markdown.github.io/. See Python-Markdown/markdown#601
for details. The docs now point to the new location.
The Python-Markdown GitHub repo was also moved to
https://github.com/Python-Markdown/markdown so any links to the repo
have been updated as well.
=> Remove PyPI Deployment Docs.

docs/about/release-notes.md
Outline that the path where the search index is written to has changed slightly from `mkdocs/` to `search/`.
See https://github.com/mkdocs/mkdocs/blob/0.16/mkdocs/commands/build.py#L342 vs https://github.com/mkdocs/mkdocs/blob/master/mkdocs/contrib/legacy_search/__init__.py#L40
=> Update Release Notes regarding Search plugin.

docs/index.md
This probably needs some improvement as the manpage generation script uses `python setup.py...` but we only document installing via pip so there is no setup.py script to call/run without more work.
=> Document how to generate/install manpages.

docs/about/release-notes.md, mkdocs/utils/__init__.py
This change slightly modifies the functionality of the copy_media_files() function by changing the behavior of the unused exclude option to be a list extensions rather than a list of Unix shell patterns.
This function is only called in `mkdocs/commands/build.py` and does not use the functionality.
I also add a variable to define markdown extensions in a single place.
This change will *greatly* simplify life for a plugin developer who wishes to reused this functionality (namely me).
So my plugin to copy markdown files can simply consist of:
```python
utils.copy_media_files(config['docs_dir'], config['site_dir'], exclude = [], dirty=True)
```
in a `post_build` event.
I understand this may get rejected as there is a private refactor in progress for the next release, but please consider …
=> Use exclude keyword to skip markdown files

mkdocs/contrib/legacy_search/__init__.py
The search plugin would add its extra Javascript on each reload polluting the HTML
=> Prevent reinjection of extra Javascript files on reload

mkdocs/themes/mkdocs/css/base.css, mkdocs/themes/mkdocs/js/base.js
Fixes #406 
Added an offset parameter to the scrollspy for slightly accurate detection.
Removed animations and the addition of the `clicky` class which seemed to confuse scrollspy.
=> Added an offset parameter to the scrollspy for more accurate detection

mkdocs/themes/mkdocs/css/base.css
Fixes #1050 
Tested on Safari 11.0.2 on Mac OS X Sierra.
Haven't tried with Cinder but I assume it's the same problem, Safari simply ignores the `width: 25%` of the `col-md-3` and pushes the `col-md-9` over it. Overriding the padding and width seems to work without affecting other browsers. It's a fairly hideous workaround but aren't they all.
=> Workaround Safari bug when zooming to < 100%

mkdocs/__main__.py
This should help when providing support to users with multiple Pythons
installed on their system. The `--version` flag's output mimics pip.
Specifically, the location `mkdocs` is installed at and the Python
version it is installed under.
Typical output might look like:
$ mkdocs --version
mkdocs, version 0.17.2 from /usr/local/lib/python2.7/site-packages/mkdocs (Python 2.7)
As an example, this would have been helpful when debugging [this user problem](https://github.com/mkdocs/mkdocs/issues/777#issuecomment-360501684).
=> Provide more version info.

mkdocs/themes/mkdocs/search-modal.html, mkdocs/themes/readthedocs/search.html, mkdocs/themes/readthedocs/searchbox.html
Currently the input does not have any label or title which means is is not correctly identified by assistive technologies such as screen reader.
(You can read more about it in [this WCAG guideline](https://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140408/H65).)
=> Add a title attribute to the search input

mkdocs/themes/mkdocs/base.html, mkdocs/themes/readthedocs/base.html
Currently, page rendering is delayed until all scripts are loaded. But these scripts are not essential to the main content.
The `defer` attribute allows the browser to render the page before the scripts are completely loaded so the user can see the webpage earlier.
=> Defer scripts

docs/user-guide/writing-your-docs.md
Added a section in the documentation for formatting tables.
You need an empty line above the table in order for it to render.
Maybe there is a better way of phrasing it than I did, but please add it to the docs, as it would be helpful.
=> Added an update in the documentation for Tables

setup.py
Changed to `"tornado>=4.1,<5.0"` in 0.17 branch. See #1427 for more info.
=> Backport temp fix for tornado 5 update

mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
We don't need most of the functionality in pathname2url so we might as
well only use the part we need. Fixes #1429.
=> Simplify path_2_url.

docs/about/release-notes.md, mkdocs.yml, requirements/project.txt, tox.ini
Uses the `mdx_gh_links` Markdown extension. Fixes #644.
=> Link to GitHub issues from release notes.

docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/tests/config/config_options_tests.py, mkdocs/themes/mkdocs/nav.html, mkdocs/themes/readthedocs/breadcrumbs.html, mkdocs/themes/readthedocs/versions.html
This adds support for GitLab repositories in the same way that already exists for GitHub and Bitbucket.
Note that the icons in the themes will not show up until FontAwesome is updated to at least version 4.6 and/or an up-to-date version of the upstream readthedocs css is imported.
This commit also fixes a slight documentation error regarding the default value of `repo_name` and removes some tautological tests.
=> Add support for GitLab repositories

docs/index.md
"Officially added support for Python 3.6 (#1296)" as of version 0.17.0.
Source: http://www.mkdocs.org/about/release-notes/#version-0170-2017-10-19
=> Noted support for python 3.6

docs/about/release-notes.md, docs/user-guide/configuration.md, docs/user-guide/custom-themes.md, docs/user-guide/styling-your-docs.md, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/plugins.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/config/config_tests.py, mkdocs/tests/plugin_tests.py, tox.ini
Ran into #543 today, saw that no one had started working on this, so decided to take a stab at it. I used `pre_validation` to coerce relative paths to absolute paths, which worked for my use case. 
Two things I wasn't sure of where to go with:
1. What happens if `Config.load_file` is passed something without a filename? I found a few tests where that was the case, but couldn't think of a use case otherwise. I reverted to the current behavior in this scenario (relative paths are left alone, so they're relative to the current working directory).
2. A few of the tests relied on the current behavior (they processed config files in `/tmp`, and relied on  the existence `./docs` in order to pass validation. I cleaned up the tests, but used `tempfile.TemporaryDirectory`, which doesn't exist in …
=> Paths in config file are relative to the config file.

README.md
The png versions of the badges can appear blurry on certain screen sizes. For me they look like this:
This PR uses the svg versions instead, which fixes that issue. It also uses the rounded version of the landscape.io 'health' badge to match the others.
=> Use .svg badges in README instead of .png

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/tests/cli_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/gh_deploy_tests.py, requirements/project-min.txt
Fixes #782. Note that we mock Markdown in the tests to ensure those
tests are not using Markdown to validate the extension names. We don't
mock Markdown in the tests which we do want Markdown to validate the
extension names.
=> Improve Markdown extension error messages.

mkdocs/templates/sitemap.xml
Google Search Console complains about empty lastmod,
I validate sitemap.xml with empty lastmod, it is invalid as in this screenshot https://prnt.sc/j2w2ws
=> Hide empty lastmod tags in sitemap.xml

mkdocs/commands/gh_deploy.py, mkdocs/tests/base.py, mkdocs/tests/gh_deploy_tests.py
If/when deploying to usr/org pages, the deploy script is run from the
Pages repo, not the project repo. Therefore, we need to get the current
sha from the project repo. Related to #1455 and #1376.
=> Ensure deploy commit message points at correct sha.

docs/about/release-notes.md, mkdocs/__main__.py, mkdocs/commands/gh_deploy.py, mkdocs/tests/base.py, mkdocs/tests/cli_tests.py, mkdocs/tests/gh_deploy_tests.py
Fixes #640.
This was a pretty straightforward change. but its not clear how this should be tested. Obviously, mocks can be used to simulate different return values (for the versions), but the behaviors we need to test are checking for various logging messages.
At this point, let's see if the current changes break any existing tests.
=> Warn users deploying with older version.

mkdocs/tests/config/config_tests.py
The previous version worked only when `../mkdocs` was pointing back to the current directory.
Fixes #1490.
=> Make test_doc_dir_in_site_dir work with custom build path

mkdocs/tests/gh_deploy_tests.py
The tests are supposed to pass when Git is not installed.
However recently two commits broke it:
- in ef93dc6b a new test was added which did not have the necessary mocks;
- in e5c2459f the `_check_version` function was added, and the tests did not have mocks for it.
With this pull requests, the tests pass again without Git.
=> Make the tests pass when git is not installed

mkdocs/commands/serve.py
The serve command overwrites the the site_dir and can cause a crash when
clean_directory tries to remove files with Unicode chars in their
filenames if the paths are byte strings. As os.path.join and friends
will return a byte string (in PY2) if any part is passed in is a byte
string, we must ensure all parts are Unicode strings. By passing a
Unicode string to prefix, tempfile.mkdtemp returns a Unicode string
rather than the default byte string in PY2. Fixes #1516.
This needs tests. However, the entire `mkdocs.commands.serve` module is untested, so this will have to wait until I have time to create tests for the entire module. I suspect lots of mock objects will be involved.
=> Use Unicode for server temp dir.

mkdocs/contrib/search/templates/search/main.js
After the pages refractor #1504 (good work btw) the resulting urls are malformed (relatives) when using the search feature in the default theme.
It can be reproduced with a simple search. Given this directory structure:
```
docs/
├── foo.md
└── index.md
```
Searching for `foo` will result in `http://127.0.0.1:8000/.foo/` instead of `http://127.0.0.1:8000/foo/`
=> Fix search result url in default theme

mkdocs/nav.py
With [PEP 479](https://www.python.org/dev/peps/pep-0479/) implemented in Python 3.7, raised `StopIteration` is now translated into `RuntimeError`, which breaks `mkdocs build` command.
The recommended way to exit generators is to use `return` instead of raising `StopIteartion`: https://www.python.org/dev/peps/pep-0479/#id39
Fixes #1518.
=> Fix Python 3.7 and PEP 479 incompatibility

docs/about/release-notes.md, mkdocs/__init__.py
I should have done this a while ago. At least back when I broke out the 0.17 branch to backport some bug fixes (0.17.3).
=> Up version to 1.0.dev

mkdocs/themes/mkdocs/css/base.css
The sidebar was under the left margin of the main content and not 
clickable. This moves the sidebar to the top so it is accessable. Not 
sure when this got broken. Maybe #1387 or #1389 or #1395.
=> Fix mkdocs theme TOC.

docs/about/release-notes.md, docs/user-guide/writing-your-docs.md, mkdocs/structure/pages.py, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/meta.py
Still needs tests and docs.
If the frontmatter is surrounded by YAML deliminators, then it is parsed 
as YAML. Otherwise it is parsed as Multimarkdown meta-data and returned 
as a string only.
This should address #1471.
=> Add support for YAML meta data.

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/tests/config/config_tests.py, mkdocs/theme.py, mkdocs/utils/__init__.py
Finalize some deprecations started in version 0.17. 
* Empty `extra_css` and `extra_javascript` settings no longer raise a warning.
* `theme_dir` config fully Deprecated. 
* Missing theme config file raises an error.
=> 1.0 deprecations

docs/about/release-notes.md, mkdocs/config/base.py
This provides a clearer error for users who have an invalid config file. 
Partially addresses #1543.
=> User friendly YAML parse errors.

docs/about/release-notes.md, docs/user-guide/styling-your-docs.md, mdl_ruleset.rb, mkdocs/tests/config/config_tests.py, mkdocs/tests/theme_tests.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/mkdocs/js/base.js, mkdocs/themes/mkdocs/keyboard-modal.html, mkdocs/themes/mkdocs/mkdocs_theme.yml, mkdocs/themes/readthedocs/js/theme.js
In both built-in themes, the default next/prev shortcut keys were 
changed from arrows to `n`/`p` as the arrows conflict with common browser 
accessibility extensions.
In the `mkdocs` theme,  users can now configure the shortcuts to whatever 
they want. Note that these config options are theme specific. The 
`readthedoc`s theme does not get these options as they are not available 
on the parent theme.
Fixes #1502
=> Don't conflict with accessibility shortcuts.

docs/user-guide/styling-your-docs.md, mkdocs/tests/config/config_tests.py, mkdocs/tests/theme_tests.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/mkdocs/mkdocs_theme.yml
This is primarily to allow third party themes which inherit from the 
mkdocs theme (such as the bootswatch themes) to alter the code 
highlighting style. Previously all of the themes hosted their own 
highlighting styles, but now that we are using the CDN, it is easier to 
use a setting, which downstream themes can override.
=> Add hljs_style config to mkdocs theme.

readthedocs.yml
The Read the Docs [mirror of the documentation](https://mkdocs.readthedocs.io/en/stable/) does not build correctly. The main issue is that the dependencies (notably the `mdx_gh_links` extension) was not installed. Here's a [recent build](https://readthedocs.org/projects/mkdocs/builds/7552464/) as an example.
This proposed PR uses [Read the Docs' yaml config](https://docs.readthedocs.io/en/latest/yaml-config.html) to specify the requirements file and to install mkdocs from the synced repository. That way the same version of mkdocs is used to build the documentation as the version that the repo contains (eg. 0.17.5 is used to build 0.17.5 and so on).
=> Fix building for Read the Docs' mirror

mkdocs/themes/readthedocs/nav.html
Fixes #1575.
The pages refactor resulted in the URL of the homepage being an empty string, which was causing the template to fail to recognize the nav item as a page and treating it like a section. By actually checking the item type, we avoid that problem.
=> Fix RTD Navigation bug.

mkdocs/contrib/search/templates/search/main.js, mkdocs/contrib/search/templates/search/worker.js, mkdocs/themes/readthedocs/css/theme_extra.css, mkdocs/themes/readthedocs/js/theme.js
Fixes #1584 
We had a copy of `initSearch` running on document ready in `main.js` which was causing the race condition with the fetching of the index and initialization.
We now explictly send a message from the initialization code to start off search for the query string if any.
I also tweaked the behaviour of the search input for the RTD theme so it does not reload the page when pressing Enter.
=> Worker search query string

mkdocs/structure/pages.py, mkdocs/tests/structure/page_tests.py
=> Ignore absolute links in Markdown.

docs/user-guide/styling-your-docs.md
As pointed out in #1633 the example of overriding a template block used an undefined block name. The example has been updated to use an actual block name.
=> Example now matches actual usage.

docs/user-guide/configuration.md
=> fix docs error --dev-addr instead of --dev_addr

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs.yml, mkdocs/commands/build.py, mkdocs/config/config_options.py, mkdocs/contrib/search/__init__.py, mkdocs/contrib/search/search_index.py, mkdocs/contrib/search/templates/search/lunr.js, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/search_tests.py, setup.py
[Many moons ago](https://github.com/mkdocs/mkdocs/issues/859#issuecomment-251216390) there was a discussion that sparked my interest in creating [lunr.py](https://github.com/yeraydiazdiaz/lunr.py). Today I released v0.5.2 introducing multilanguage support and I feel it's time to bring it back to the source 🙂 
Changes include:
- Adding `lunr[languages]>=0.5.2` as a dependency, more on this later
- `prebuild_index` is now a string with two possible values `node` or `python`, directing the search plugin to use lunr.js or lunr.py respectively
- Update bundled lunr.js version to 2.3.2
I went for the more direct approach: requiring lunr + language support which in turn pulls NLTK as a dependency. This may not be desirable but it's the only way to guarantee complete support and it's roughly what …
=> Use lunr.py for prebuilding indices

mkdocs/themes/mkdocs/css/base.css
The `font-family: monospace,serif;` was not working on Android 8 Chrome 69, causing code blocks to render with some variable width serif font. This change copies the --font-family-monospace variable value from the bootstrap css file in the same directory. You could alternatively use `var(--font-family-monospace)` or even remove the `font-family` declaration here and rely on the style for pre in `bootstrap.custom.min.css`.
=> Fix monospace code rendering on Android

docs/about/release-notes.md, mkdocs/structure/files.py, mkdocs/structure/pages.py, mkdocs/tests/structure/file_tests.py, mkdocs/tests/structure/page_tests.py, mkdocs/utils/__init__.py
Encode URLs of all internal documents (to account for spaces in 
filenames, etc). Then unencode Markdown links to internal pages before 
confirming existence, etc. Fixes #1670.
=> Account for encoded URLs.

docs/user-guide/plugins.md
plugins.md:357
"The `post_template` event .." -> "The `post_page` event .."
=> docs(plugins.md): fix typo

docs/user-guide/plugins.md
Docs are outdated: site_navigation -> files in almost all of the events.
=> docs(plugins.md): outdated docs

mkdocs/commands/build.py, mkdocs/plugins.py, mkdocs/structure/pages.py, mkdocs/tests/plugin_tests.py
The current event implementation is a bit limited. The idea of having events revolve around an item is cool; you pass an item to run_event, it loops through all the available event handlers, calls them with the item and if they return anything it reassigns the item to the return value, finally returning the item's final iteration, possibly completely different from the one passed in. Unfortunately this doesn't accommodate events that don't revolve around an item, which are only used as callbacks, such as pre_build and post_build, or even events that are for creating a new item, such as page_read_source.
I've changed `run_event` by making `item` optional (defaulting to `None`). If an item isn't provided it doesn't get passed to the event handlers. This doesn't mean that the event handlers …
=> Overhaul events

mkdocs/commands/new.py, mkdocs/tests/integration/minimal/docs/testing.md, mkdocs/tests/integration/unicode/docs/Übersicht.md, mkdocs/tests/integration/unicode/docs/♪.md
Just using "https://mkdocs.org" yields a certificate error because that is the GitHub wildcard certificate, so the domains don't match.
=> Fixed default link in new page

mkdocs/utils/__init__.py, tox.ini
The `mkdocs/compat.py` file had been deleted some time ago so we don't need to "exclude" it anymore.
=> Flake8 cleanup

docs/user-guide/writing-your-docs.md
Regarding #1757. An update to the docs to warn about the dangers of absolute paths in links.
I am not sure if you guys manually break lines or there is some tool to do it, so I just left them as is for now. I know it's not going to be merged like this, but I couldn't find anything on this in the contributing guidelines. Let me know what's the official way to go about this an I'll fix it.
=> Warning about the usage of absolute paths in links

docs/about/contributing.md
* contributing.md:52-53
"needs
to be pip installed ..." 
-> "needs
[pip](https://pypi.org/project/pip/) to be installed ..."
* contributing.md:53
"then the test suite can be ran for MkDocs but running ..." -> "then the test suite can be run for MkDocs by running  ..."
=> contributing.md: fix typos, add link

.travis.yml, mkdocs/tests/cli_tests.py, mkdocs/utils/ghp_import.py, tox.ini
Travis has changed their default Python version from 2.7 to 3.6 on April 16, 2019 in anticipation of PY27 support being dropped in 2020. The `basepython` setting isn't nessecary as the tests will run by default in whichever version tox is called from. As we can be sure that version exists on the platform, it is best to use that version and avoids the need for future changes.
This avoids test failures like the [this](https://travis-ci.org/mkdocs/mkdocs/jobs/521064818) and [this](https://travis-ci.org/mkdocs/mkdocs/jobs/521064816).
=> Update Travis config for default Python 2.7=>3.6

mkdocs/themes/readthedocs/base.html
- no need for `type/css` in HTML5 documents
- having `rel="stylesheet"` first can improve readability/scannability of the code and as it's more consistent aids with gZip compression.
- no need for closing `/` in HTML5 documents
REF:
- http://codeguide.co/  (Bootstrap Styleguide)
- https://google.github.io/styleguide/htmlcssguide.html  (Google Styleguide)
=> Tidy up CSS link formatting

docs/user-guide/custom-themes.md
This only updates the documentation to better reflect actual behavior.
The config for `theme.custom_dir` is defined in the `theme` config
option of `mkdocs.yml`. Therefore, any `mkdocs_theme.yml` file within
a `custom_dir` is ignored.
Thanks to @k4kfh for the suggestion in squidfunk/mkdocs-material#751.
=> Clarify that `mkdocs_theme.yml` is ignored by `theme.custom_dir`

docs/user-guide/deploying-your-docs.md
The `features` link was not broken per-se, but I figured the old link wasn't the canonical one either. :-)
Thanks!
=> Fix broken readthedocs links

docs/user-guide/writing-your-docs.md
Only atx-style headers are supported for page titles, not Setext styles.
Refs #1837
=> Docs: Clarify supported header style

docs/user-guide/configuration.md, docs/user-guide/writing-your-docs.md
Add links to the section about page titles.
=> Docs: Clarify page title generation

docs/user-guide/configuration.md, docs/user-guide/writing-your-docs.md
The YAML indentation in the examples is wrong.
=> Docs: Fix YAML syntax in examples

mkdocs/themes/mkdocs/base.html
Bootstrap 4.x doesn't work with IE8 at all.
IE8 marketshare is now just 0.1% anyway (https://caniuse.com/usage-table)
=> Remove unneeded IE8 polyfills

mkdocs/templates/sitemap.xml
Currently special characters such as `&` result in a `xmlParseEntityRef: no name` error and make the xml fail to display
=> Escape special characters in sitemap.xml

mkdocs/themes/readthedocs/search.html
Simple change to 'search.html' template.
Closes #1791
=> Change 'search.html' in the Read the Docs theme to extend 'main.html'

docs/about/release-notes.md, mkdocs/commands/gh_deploy.py
Currently if you try to run `gh-deploy` without git installed you get a fairly unhelpful backtrace, that will lead you to the thread for #722 if you google it.  This adds a more helpful error message.
=> Provide sensible error message when git not found

docs/about/release-notes.md, mkdocs/commands/serve.py
As of Python 3.8, the default event loop on Windows is `proactor`,
however Tornado requires the old default "selector" event loop.
As Tornado has decided to leave this to users to set, MkDocs needs
to set it. See https://github.com/tornadoweb/tornado/issues/2608.
Fixes #1885.
=> Select asyncio event loop on Windows for PY3.8+

docs/about/release-notes.md, docs/user-guide/styling-your-docs.md, mkdocs/tests/config/config_tests.py, mkdocs/tests/theme_tests.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/mkdocs/mkdocs_theme.yml
See also: https://github.com/mkdocs/mkdocs-bootswatch/issues/56
This patch allows documentation authors to configure the color of the navigation bar with one of three options (defined by the Bootswatch theme): `primary` (the default), `dark`, and `light`. This is primarily here to restore support for (what used to be called) inverse nav headers in mkdocs-bootswatch. Without this patch, mkdocs-bootswatch would have to redefine all of `base.html` for each theme to include the changes made here. Since this feature is relevant for the `mkdocs` theme, I figured it made more sense to add it in the base theme.
The Jinja template change is a bit hairy here, but I'm not sure if there's a better way to do it...
Here are some examples of what it looks like with the `mkdocs` theme:
`primary`
`dark` …
=> Add support for customizing navigation bar styles in the MkDocs theme

mkdocs/themes/mkdocs/css/base.css
This patch uses `scroll-padding-top` to indicate that when the user clicks on an anchor and the browser scrolls to it, the anchor should have that amount of padding on the top, thus neatly accommodating the fixed nav header without any gross hacks!
Note: I used a padding of 70px to match the body's padding, rather than 75px as the old CSS hack used. Probably doesn't matter too much either way, but this seems more consistent...
=> Properly handle the scroll offset for anchors in the mkdocs theme; resolves #1931

docs/user-guide/writing-your-docs.md
You can see the failing test this is supposed to address here: https://travis-ci.org/mkdocs/mkdocs/jobs/627731199#L525
I'm assuming this started to fail due to a recent update to the linter. I believe the old ruby linter we used to use complained that we used a different number of backticks, which is why we previously used tildes to wrap backticks within a code block. The JS linter properly recognizes that you need a different number of backticks to wrap backticks within the code block.
=> Cleanup MarkdownLint issue in docs.

docs/about/release-notes.md, requirements/project-min.txt, setup.py
Jinja 2.10.1 patched a security valnerability. See the release notes here:
https://github.com/pallets/jinja/blob/master/CHANGES.rst#version-2101
Closes #1780.
=> Update min dependency to Jinja 2.10.1.

mkdocs/commands/build.py, mkdocs/commands/gh_deploy.py, mkdocs/commands/new.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/search_tests.py, mkdocs/tests/structure/page_tests.py, requirements/test.txt, tox.ini
The nose docs state:
> Nose has been in maintenance mode for the past several years and will
> likely cease without a new person/team to take over maintainership.
> New projects should consider using Nose2, py.test, or just plain
> unittest/unittest2.
As we aren't really using any of nose's features, its easiest to switch
to the standard lib unittest.
**Note** This is currently experimental. I'm checking to see how many tests fail and if there are differences across platforms. Is it more work than its worth?
=> Switch from nose to unittest.

docs/about/release-notes.md, mkdocs/structure/pages.py, requirements/project-min.txt, requirements/project.txt, setup.py
This cleans up the last two warnings issued when tests are run from #1434.
=> Update min Markdown version to 3.0.

docs/index.md, docs/user-guide/plugins.md
Since I’ve refactored and extended the MkDocs Plugins wiki page ( https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins ), I thought it’d be a good idea to improve its visibility by adding a link from the docs. I’m also adding a few more links to better connect the introduction with the user guide.
=> Links to the MkDocs Plugins wiki page, a few extra links regarding user guide, themes and plugins

mkdocs/themes/readthedocs/base.html
Not needed for HTML5 documents (and this isn't used elsewhere).
=> remove unneeded  type="text/javascript"

mkdocs/themes/mkdocs/css/base.css, mkdocs/themes/mkdocs/js/base.js
This patch allows dropdowns with many items to scroll, rather than overflowing beyond the bounds of the page. Due to the complexities of CSS, this requires nested dropdowns to be given a fixed position which is initialized via JS.
In addition, this patch changes the behavior of nested dropdowns to require a click to open (more consistent with the root dropdown, and improves UX on mobile devices). It also fixes the UI on small screens, adding the nested dropdown "in-place" when it's opened and allowing the whole navbar to scroll if there are many items.
=> Improve support for long dropdowns in the mkdocs theme

docs/about/release-notes.md, mkdocs/themes/mkdocs/css/base.css, mkdocs/themes/mkdocs/js/base.js
This resolves #716. The original issue there is already fixed on master, but the issue with the nav header at the end of the discussion was still happening.
This adds a new JS function called `applyTopPadding` that updates the top padding of a few elements in the document to account for the height change when the nav header is more than one row. Sadly, I don't think there's a way to do this without at least a little JS (at least, not yet...).
I also fixed the whitespace in `themes/mkdocs/js/base.js`, since I accidentally used 2-space indentation in a previous commit...
=> Improve support for tall nav headers in the mkdocs theme

mkdocs/themes/mkdocs/css/base.css
Previously, opening a dropdown from the mobile-sized nav header would break things if the user resized the window to be desktop-sized again. This was due to an attempted fix to allow the mobile-sized nav header to scroll when it had many elements.
This patch now only does that when the header is in mobile mode.
=> Fix fallout from #1967

mkdocs/structure/nav.py
This PR is motivated by the discussion #1983.
It constitutes a minor rephrasing of a comment in [L120-121](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/nav.py#L120-L121) in `nav.py` to make it extra clear what happens in the following two lines and that the functionality is correct.
=> Minor rephrasing of comment to clarify the code intent

docs/user-guide/configuration.md
`"and appropriate relative URL"` -> `"an appropriate relative URL"`
=> Minor typo fix in the docs

docs/about/contributing.md
Thanks a lot for MkDocs and to everyone who has contributed to it!
Minor issue: the link to the virtualenv user guide in the [contributing](https://www.mkdocs.org/about/contributing/#installing-for-development) section of the docs is broken.
This PR fixes that.
=> Fix link to virtualenv user guide (in contributing section of the docs)

.travis.yml, docs/about/release-notes.md, docs/user-guide/custom-themes.md, mkdocs/structure/files.py, mkdocs/tests/structure/file_tests.py
Also, document how all files within themes are treated by MkDocs.
Fixes #1981.
=> Ensure nested dot files in themes are ignored.

mkdocs/themes/mkdocs/css/base.css
This is a tiny fix. It's only really here to keep this file somewhat in sync with its counterparts in mkdocs-bootswatch. That way, most changes to base.css can be applied automatically. :)
=> Fix indent width in mkdocs/themes/mkdocs/css/base.css

docs/about/release-notes.md, docs/user-guide/styling-your-docs.md
Despite Bootswatch not supporting nested dropdowns, the theme-specific CSS for the mkdocs theme does add support for it, so we can remove the warning from the release notes. See also #1967.
=> Nested dropdowns *are* supported in the mkdocs theme

mkdocs/themes/mkdocs/base.html
This behavior matches MkDocs 1.0 as well as the examples on the Bootswatch site. The HTML just needed a bit of re-arranging to match how Bootswatch expects things to be. I tested this with the base `mkdocs` theme as well as the `mkdocs-bootswatch` themes.
(The white background for the dropdowns is a bit ugly in my opinion, but it's how things look in the Bootswatch demos...)
Before:
After:
=> Put the mobile menu button for the mkdocs theme on the right

setup.py
Each version of lunr.py only works with a specific version of lunr.js.
Therefore we must hardcode the specific version of lunr.py in our
requirements. As we recently updated to lunr.js version 2.3.8 (#1995),
that coincides with lunr.py version 0.5.6. See the lunr.py CHANGELOG for
coinciding versions: https://github.com/yeraydiazdiaz/lunr.py/blob/master/CHANGELOG.md
=> Ensure lunr.py version matches lunr.js

docs/about/release-notes.md
The release note describes:
>* Update minimum dependancy to Markdown 3.0.1.
However, the actual minimum dependency of Markdown package at mkdocs 1.1 is 3.2.1.
https://github.com/mkdocs/mkdocs/blob/eddeeab066cb071dbe426878a85de715df1b93e7/requirements/project.txt#L4
=> Fix a minimum dependency description of Markdown at the release note

mkdocs/themes/mkdocs/search-modal.html
doesn't make a difference to how it works but is more semantically correct.
=> Use type search for search input

docs/user-guide/styling-your-docs.md
As mentionned here: https://github.com/mkdocs/mkdocs/issues/1142#issuecomment-282899537
I just correct the name in the documentation
=> Correct the block name of the search box in the doc

setup.cfg
MkDocs no longer supports Python 2. Therefore, a universal wheel would be
inappropriate as it results in `py2.py3`.
See Python-Markdown/markdown#919.
=> Ensure bdist_wheel no longer creates a universal wheel

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/integration/complicated_config/mkdocs.yml
MkDocs has never supported using the included server for production.
However, some users have been using it that way. This would prevent that.
Still needs proper tests. However, a quick test on the command line produces these results:
```
λ mkdocs serve -a 0.0.0.0:8000
INFO    -  Building documentation...
ERROR   -  Config value: 'dev_addr'. Error: The MkDocs' server is intended for 
development purposes only. Therefore, '0.0.0.0' is not a supported IP address.
Please use a third party production-ready server instead.
Aborted with 1 Configuration Errors!
λ mkdocs serve -a 277.0.0.0:8000
INFO    -  Building documentation...
ERROR   -  Config value: 'dev_addr'. Error: '277.0.0.0' does not appear to be an
IPv4 or IPv6 address
Aborted with 1 Configuration Errors!
```
=>  Disallow 0.0.0.0 dev_addr.

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/contrib/search/__init__.py, mkdocs/contrib/search/templates/search/main.js, mkdocs/contrib/search/templates/search/worker.js, mkdocs/tests/search_tests.py
As mentioned in [issue 2014](https://github.com/mkdocs/mkdocs/issues/2014), searching for any term of less than 3 characters will give the user back a message saying 'No results found' - This is misleading as results may have been present, but due to a hardcoded limit on minimum search length the search was not actually performed.
This PR implements an additional config parameter `min_search_length` for the search plugin.
=> Support for minimum search length configuration parameter.

docs/about/release-notes.md, mkdocs/themes/readthedocs/css/theme_extra.css
Some CSS overrides. See images for Sphinx, mkdocs 1.0.4 and mkdocs 1.1 (without/with PR) comparison.
=> fix #2027 code colors

docs/index.md
Updated installation information to include Python 3.8 support, and dropped 2.7/3.4 support.
- 2.7 is EOL and no longer supported by MkDocs: #1936 
- 3.4 is EOL and no longer supported by MkDocs: #1938 
- 3.8 supported by MkDocs: #1938
=> 3.8 is supported; 2.7 and 3.4 are not anymore

mkdocs/config/config_options.py
If the config file was inside the docs dir, mkdocs would give a
confusing error:
config value: 'docs_dir'. Error: The 'docs_dir' should not be the parent directory of the config file. Use a child directory instead so that the config file is a sibling of the config file.
The last part of that message now reads:
Use a child directory instead so that the 'docs_dir' is a sibling of the config file.
Fixes https://github.com/mkdocs/mkdocs/issues/2009
=> Correct error message

mkdocs/__main__.py
The `click` configuration would be no longer needed.
Since `mkdocs` already dropped Python 2 support and removed the `unicode_literals` import:
```
from __future__ import unicode_literals
```
=> Remove disable_unicode_literals_warning config

docs/about/release-notes.md, setup.py
Lunr.py version 0.5.8 maintains compatability with Lunr.js 2.3.8, but
restricts its dependnecy to `nltk>=3.2.5,<3.5`, which avoids installation
issues on some Docker images. Fixes #2062.
=> Set dependency to `lunr[languages]==0.5.8`.

mkdocs/__main__.py, mkdocs/tests/cli_tests.py
This should have been removed some time ago. Fixes #2042.
=> Remove deprecated theme_dir option from CLI.

docs/about/release-notes.md, docs/user-guide/plugins.md, mkdocs/commands/serve.py
Every call to `server.watch` requires `builder` to be passed in. If
users are to add their own watched files, then they need access to
`builder`. Fixes #1952.
=> Pass builder to on_serve event.

docs/about/release-notes.md, mkdocs/structure/files.py, mkdocs/tests/structure/file_tests.py
Right now, just like any *foo/index.md*, any *foo/README.md* becomes *foo/index.html*, but that works only if `use_directory_urls` is on.
But the `use_directory_urls` feature is for changing *foo/bar.md* into *foo/bar/index.html* and should not prevent the former from working.
I'm hoping that this is more of an oversight (due to the source code for the two things being very related) than an intentional exclusion.
So I'm sending a small pull request to fix that and also unify the code paths. But feel free to discuss this as an issue in case it's not as agreeable as I thought.
=> Use README.md as index.html also if use_directory_urls is false

.travis.yml, docs/user-guide/custom-themes.md, tox.ini
Just experimenting trying to understand why the markdownlint test is failing.
=> Fix markdownlint test

docs/about/release-notes.md, mkdocs/commands/build.py, mkdocs/structure/pages.py, mkdocs/tests/build_tests.py, mkdocs/utils/__init__.py
Our deployment step for https://datadoghq.dev/integrations-core/ should only trigger when a change occurs in the built site. However, every build was different because gzip includes the timestamp in its header.
This fixes it by setting the field to zero.
cc @waylan since you were involved with https://github.com/mkdocs/mkdocs/pull/1130
=> Make compressed sitemap deterministic

docs/about/release-notes.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
All IP addresses passed to `dev_addr` are now normalized.
`127.000.000.001` is normalized to `127.0.0.1`.
With apologies to docker container users, the address `0.0.0.0`
no longer raises an error but a warning instead. Apparently,
docker containers need to use that address, even in dev environments.
Closes #2108.
=> Normalize IP addresses and change error to warning

docs/about/release-notes.md, mkdocs/__init__.py
Apparently 1.1.1 is completely useless to those who use MkDocs in a Docker Container. Therefore, we are releasing a fix immediately. Sorry for the inconvenience.
=> Bump version to 1.1.2.

docs/user-guide/plugins.md
Add helpful link for plugin developers. I used the 'master' branch of jinja so link will not break on future versions of `jinja2`
=> Add link to Jinja environment class

docs/user-guide/writing-your-docs.md
On the Writing Your Docs page, the link in the text links to `index_pages` with an underscore but the page as currently rendered has that link as `index-pages` with a hyphen.  This corrects that link.
=> Fix relative link to Index Pages in Writing Your Docs help page

mkdocs/config/config_options.py
This fixes below warning for Python 3.10 compatibility. 
```
/root/py39-venv/lib/python3.9/site-packages/mkdocs/config/config_options.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
from collections import Sequence, namedtuple
```
=> Import ABC from collections.abc explicitly.

docs/about/release-notes.md, mkdocs/__init__.py, mkdocs/__main__.py, mkdocs/commands/serve.py, mkdocs/tests/cli_tests.py
Add a `--watch-theme` option which theme devs can enable if needed.
Most users never modify the theme files and watchers are resource hogs.
Fixes #2092.
=> Exclude theme from watched files by default.

docs/about/release-notes.md, mkdocs/__main__.py, mkdocs/commands/serve.py, mkdocs/tests/cli_tests.py
This should address #2061. However, I don't perceive any actual delay. Perhaps those who have a need for could report back.
```
$ mkdocs serve --wait 60
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.96 seconds
[I 200505 14:43:49 server:296] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 200505 14:43:49 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 200505 14:43:49 handlers:64] Start detecting changes
INFO    -  Start detecting changes
[I 200505 14:43:53 handlers:135] Browser Connected: http://127.0.0.1:8000/
INFO    -  Browser Connected: http://127.0.0.1:8000/
[I 200505 14:44:07 watcher:104] Running task: builder (delay: 60)
INFO    -  Running task: builder (delay: 60) …
```
=> Add --wait flag to serve command.

docs/index.md
We already link to the Deploying for Docs page which includes specific
instructions for various hosts. There is no need to also link to those
hosts in the Getting Started guide.
Closes #2210, closes #2104, closes <del>#1494</del> <ins>#1890</ins>.
=> Remove links to specific hosts from Getting Started Guide

.github/workflows/tox.yml
Hi, I noticed from the tox issue that you disabled pypy for Windows. I found a simple workaround that seems like a good enough solution at least until the new pypy is released on GitHub Actions.
=> Reintroduce pypy to CI

mkdocs/contrib/search/search_index.py, mkdocs/structure/files.py, mkdocs/structure/pages.py
This has proven to be very significant in profiling:
Before:
|ncalls|tottime |percall  |**cumtime** |percall  |filename:lineno(function)|
|------|--------|---------|--------|---------|-------------------------|
|128695|0.1908  |1.483e-06|**1.169**   |9.082e-06|pages.py:46(`__eq__`)      |
|**119617**|0.12    |1.003e-06|**0.4357**  |3.643e-06|files.py:127(`__eq__`)     |
After:
|ncalls|tottime |percall  |**cumtime** |percall  |filename:lineno(function)|
|------|--------|---------|--------|---------|-------------------------|
|128695|0.06688 |5.197e-07|**0.08264** |6.421e-07|pages.py:46(`__eq__`)      |
|**1842**  |0.001276|6.926e-07|**0.001434**|7.787e-07|files.py:127(`__eq__`)     |
=> Optimize/simplify __eq__ implementations

mkdocs/theme.py
MkDocs templates are quite heavily split into files and [can even be nested][1] (particularly for navs, which also repeat on every page).
Any time a template is referenced, even though it's cached in memory, Jinja ends up doing a filesystem access, to check whether the template file has been modified and so would need to be recompiled.
But it's not even useful to be able to modify a template file on disk in the middle of a mkdocs build.
So, by disabling autoreload, we eliminate all these filesystem accesses (on the order of thousands), other than the initial one per template.
The lifetime of the Jinja environment is the lifetime of a `mkdocs build`, and a `mkdocs serve` creates a new one each time anyway, so that is not affected.
---
For my site of 134 pages with a heavily nested nav (w/ …
=> Don't check the filesystem for edits to template files during a build

mkdocs/contrib/search/search_index.py
As far as I can tell, a Python `str` type can never be not encodable as UTF-8, so this doesn't check anything. And if it was `bytes` instead, well, it just doesn't have an `encode` method.
Last code change was here: https://github.com/mkdocs/mkdocs/commit/c9032bd6bfde09ead2f4f879e85590d7cd6e68a6#diff-c415bde0ad17e1a44da9e86aabf2f6ee0c21fd38ae9c459bea6589bcc61d0efbR46
=> Don't needlessly encode a string, that's a holdover from Py2 compat

mkdocs/commands/build.py
I.e. this list now gets formed a constant numer of times within a mkdocs build, instead of also doing it once per page
For compatibility (if someone happened to use this function externally), one can still pass a `Files` to get_context, but its main mode of operation is now to accept a direct list of `File`s
=> Don't re-query the list of doc pages for every page (for performance)

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py, requirements/project-min.txt, requirements/project.txt, setup.py
Environment variables can be assigned as values in the configuration file using the `!ENV` tag. Resolves #1954.
The behavior is defined in the third-party package [pyyaml_env_tag](https://github.com/waylan/pyyaml-env-tag).
=> Support Environment Variables in config file

mkdocs/contrib/search/search_index.py, mkdocs/tests/search_tests.py
This improves performance, as HTML of each page doesn't need to be parsed twice.
~Also replace list->string joining with StringIO, as that's very slightly faster and slightly more idiomatic.~
=> search: Merge the postprocessing done by two HTML parsers into one

mkdocs/__main__.py
- Use message  and  version arguments of click.version_option for better syntax instead string formatting.
- Modify pgk_dir typo.
- FIx pylint: C0103.
- DRY: remove repeated call of python version and add PYTHON_VERSION.
=> Modify the syntax of version option and checking python version

mkdocs/commands/build.py, mkdocs/tests/build_tests.py
[The new BuildError exception](https://github.com/mkdocs/mkdocs/pull/2103) is good for skipping the traceback, but now that it's skipped, the two copies of the error mesage (one from logging, one from reaching `SystemExit`) end up immediately following each other, which looks strange.
So, skip logging the exception's message when encountering a `BuildError` in `_populate_page` and `_build_page`.
<details><summary>Error output for other uncaught exception (no change here)</summary>
```
INFO    -  Cleaning site directory 
ERROR   -  Error reading page 'some/page.md': Some error message
Traceback (most recent call last):
File "", line , in
zzz
File "", line , in
zzz
File "", line , in
zzz
File "", line , in
zzz
File "", line , in
zzz
some_module.SomeException: Some error message
``` …
=> Skip duplicated error message when omitting the traceback

mkdocs/utils/__init__.py
It is possible that this directory does not exist when checking but already exists when trying to create it. I ran into that when parallelizing a test suite. Now, mind you, this almost always means a bug elsewhere, but still, this is simpler code anyway.
`exist_ok` is "new" in Python 3, I guess that's why it wasn't used previously.
=> Avoid a race condition creating the subdirectory for a site file

mkdocs/config/config_options.py
When a parameter value validation fails for a plugin the name of
the failing plugin is not displayed
This commit adds the name of the plugin in the error message for
completeness
=> config_options: display the name of the plugin failing validation

docs/about/release-notes.md, mkdocs/structure/files.py, mkdocs/tests/structure/file_tests.py
Plugins wishing to manipulate the Files structure have an append
method but can't dynamically work on src_paths since it's computed
once on Files instanciation
This commits allows plugins to manipulate Files trough append and
remove of file objects while not having to care about the src_paths
since it's now a dynamically computed property
=> files structure: move src_paths as a dynamic property, add remove

docs/about/release-notes.md, docs/user-guide/configuration.md, mkdocs/contrib/search/__init__.py, mkdocs/contrib/search/search_index.py, mkdocs/tests/search_tests.py
* Allows a user to supply a `indexing` configuration to the search
plugin which controls what to include in the search index (full,
sections, titles)
* Added test coverage
* Added documentation
Resolves: #2221
=> Added configuration for search indexing strategy

mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
When only one of the two passed paths starts with a slash, this function would produce results that depend on (and expose parts of) the actual current working directory.
In a similar manner, it was also possible to "break out" of the "current directory" by starting one of the paths with `../../..` etc.
Additionally, the fact that paths always end up being resolved relative to the current working directory made this function less efficient than it needs to be.
Fun fact: `get_relative_url('path_a', 'path_b')` actually ended up looking up how to get to `/current/working/directory/path_a` from `/current/working/directory/path_b`.
Luckily, none of these behaviors can ever actually come into effect (the function is always called without a leading slash and without paths deliberately trying to …
=> Exclude edge cases where get_relative_url depends on CWD

docs/about/release-notes.md, mkdocs/config/__init__.py, mkdocs/config/base.py, mkdocs/config/defaults.py, mkdocs/tests/base.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_tests.py
Replace the global variable `mkdocs.config.DEFAULT_SCHEMA` with
the function `mkdocs.config.defaults.get_schema()`. An instance is no
longer created on import (eliminating circular imports under certain
circumstances) and each call to `get_schema()` builds a new instance
of each object. Fixes #2289.
=> Ensure each instance of Config is unique

docs/about/release-notes.md, mkdocs/themes/readthedocs/base.html, mkdocs/themes/readthedocs/js/theme_extra.js
Rather than including this is the JS form the upstream theme, the JS
has been included in a separate file `theme_extra.js` so that is is not
lost in a future update copied form upstream. Fixes #2028.
=> Restore styling of tables in the `readthedocs` theme

docs/about/release-notes.md, mkdocs/__main__.py, mkdocs/commands/serve.py, mkdocs/tests/cli_tests.py
This reverts commit f73f221f1f303cd1b5d481a263add49377c01735.
It seems that the `wait` flag does not interupt the file watcher,
but simply delays builds. Therefore, a plugin which writes to the
`docs_dir` will still result in an infinite loop. That being the
case, the `wait` flag is not useful to us. See #2285.
=> Revert "Add --wait flag to serve command."

docs/about/release-notes.md, mkdocs.yml, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/tests/config/config_options_tests.py
`urlparse(config['site_url']).path` can be empty if `site_url` does not end
in a slash. This ensures at least a slash is returned. Config validation
will add the slash if it is missing. Fixes #1785.
=> Ensure site_url ends with a slash

docs/about/release-notes.md, mkdocs/__main__.py, mkdocs/commands/build.py, mkdocs/commands/gh_deploy.py, mkdocs/commands/serve.py, mkdocs/config/base.py, mkdocs/exceptions.py, mkdocs/structure/files.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/tests/cli_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/gh_deploy_tests.py, mkdocs/tests/plugin_tests.py, mkdocs/tests/utils/utils_tests.py, mkdocs/theme.py, mkdocs/utils/__init__.py
This provides for better reporting to users, makes for easier maintenance going forward, and will allow future expandability. The following major changes were made:
1. The logging config is now defined in a way which will allow future expandability. For example, we could add additional levels of `strict` or `verbosity`. All log messages are fed to a single log, which has two handlers (one for strict mode and one for verbosity). All level restrictions are defined per handler so that one restriction does not interfere with another. As filters do not have a level assigned to them, the previous count filter is now a nullhandler which counts all messages is receives (restricted only by level). The previous filter still exists (as a do-nothing instance) for any third-party plugins which called …
=> Refactor Logging and Error handling

mkdocs/__main__.py
The new ClickHandler was causing all log messages to be printed to the
test output. As it offered no real value and littered the test output,
we are reverting back to the logging.StreamHandler with no loss of
functionality. See #2364 for context.
=> Revert to logging.StreamHandler

docs/about/release-notes.md, mkdocs/__main__.py
* Account for user's actual terminal width
* Skip wrapping if not in a terminal
* Preserve whitespace
* Avoid breaking long words and on hyphens
=> Improve CLI textwrapping

mkdocs/__main__.py, mkdocs/structure/nav.py
1. Fix handling of messages that already have multiple lines.
It looks like the wrapping code in stdlib just considers '\n' like any other character, so the result is really weird.
2. ~~Decrease indentation by one, to match the default logger.~~
3. ~~Semi-related: Drop one case of manual indentation now that it's centrally handled.~~
See examples of (1) and (2) at https://github.com/mkdocs/mkdocs/pull/2364#issuecomment-824381108
=> Fix wrapping of multiline strings for the newly added ColorFormatter

mkdocs/templates/sitemap.xml
Closes #2177
- Instead of using `nav` items for sitemap entries rendering, `[file.page for file in pages]` is used.
- Rendered `sitemap.xml` content is properly formatted using 4 spaces for indentation.
=> Include hidden pages in sitemap

mkdocs/tests/config/config_options_tests.py
[`ipaddress.ip_address`](https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Address) behaviour has been changed in Python3.9.5 due to a [security fix](https://www.ehackingnews.com/2021/05/python-affected-by-critical-ip-address.html). Now, leading zeros are not treated as part of valid ip addresses.
~~This pull proposes the change of the affected test, adding a leading zero at the beginning to make it break in earlier versions of Python, but the other option would be to delete it because this normalization would be invalid.~~
=> Update IpAddress normalization test broken in Python3.9.5

mkdocs/utils/filters.py, requirements/project-min.txt, requirements/project.txt
-- use `markupsafe.Markup` directly instead.
Note: the choice of version is to match https://github.com/pallets/jinja/blob/2.10.1/setup.py
See the deprecation message already popping up in CI:
https://github.com/mkdocs/mkdocs/runs/2567454550?check_suite_focus=true#step:5:17
`DeprecationWarning: 'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.`
=> Replace use of deprecated alias `jinja2.Markup`

mkdocs/commands/serve.py
When `mkdocs serve` is shutting down, it cleans up after itself removing the temporary directory created earlier.
Previously the condition whether the directory is to be removed was unchecked and prone to a file system race condition (shared resource).
Given the directory is absent on the file-system while shutting down, `mkdocs serve` threw an exception and exited in failure.
Change is to override the cause of the exception by preventing the attempt to remove a directory that is already gone.
=> No exception if directory already removed, closes #2420

docs/about/release-notes.md, mkdocs/commands/serve.py, mkdocs/livereload/__init__.py, mkdocs/tests/livereload_tests.py
E.g. if `site_url` is specified as `http://example.org/sub/path/`, then upon opening `http://127.0.0.1:8000/` you will be redirected to `http://127.0.0.1:8000/sub/path/`. And the file `docs/foo/index.md` will be served at `http://127.0.0.1:8000/sub/path/foo/`
Ref https://github.com/mkdocs/mkdocs/issues/2404#issuecomment-840622229
=> Offset the local site root according to the sub-path of the site_url

mkdocs/utils/__init__.py
duplicates returned by importlib_metadata during tests
instead of using lists, we use and compare on sets
thanks to @oprypin for the heads up
=> utils: fix get_themes WARNING logs due to possible entry point

mkdocs/livereload/__init__.py, mkdocs/tests/base.py, mkdocs/tests/livereload_tests.py
Watchdog doesn't support it directly but it happened to work everywhere except Windows
---
(lost in commit a444c43)
This is achieved by walking through the target directory, finding any symlinks in it, and watching their target too (+recursive walking of those too).
Important note: only symlinks that exist during startup will be taken into account, new ones aren't added.
Fixes #2425
Closes #2426
cc @ktomk
=> Restore the functionality of watching files through symlinks

docs/dev-guide/plugins.md
The behavior of this event has never changed. The documentation was simply
incorrect. Fixes #2308.
=> Correct documentation of on_pre_template event.

docs/about/release-notes.md, mkdocs/__init__.py, mkdocs/commands/gh_deploy.py
This was a regression in behavior. I had missed that `push` and `force`
are two separate parameters of `ghp_import.ghp_import` in #2257.
The old behavior has been restored (`push` is always enabled and `force` is overridable).
=> Ensure gh-deploy always pushes

.github/workflows/deploy-release.yml
I just manually deployed version 1.2 as the deploy script failed because the babel commands were not available. This fixes that. As babel is an optional dependency, we need to explicitly require it for any automated scripts.
=> babel is required for deployment

docs/about/release-notes.md, mkdocs/__init__.py
Normally I would wait for a few more bug reports/fixes to come in before making another release, but the one fix in here is needed for users deploy scripts to work. As the regression is very disruptive to users, we should get this fix out immediately (see #2444, #2447 and #2448).
=> Bump version to 1.2.1

mkdocs/livereload/__init__.py, mkdocs/tests/livereload_tests.py
=> Fix serving files/paths with Unicode characters

mkdocs/commands/gh_deploy.py
If the config file is specified as relative and is in the current directory, the `dirname` transform came out empty, which `subprocess` doesn't like as `cwd`.
Fixes #2471
=> Fix gh_deploy with config-file in the current directory

mkdocs/themes/readthedocs/breadcrumbs.html
`pages.py` and `nav.py` generate the `ancestors` property in the following way:
```
[self.parent] + self.parent.ancestors
```
This causes the parent to be first and the root to be last in the list, which is opposite to the order expected in breadcrumbs. This patch fixes it by reversing them before creating the breadcrumbs html.
Fixes #2143
=> Fix reversed breadcrumbs in rtd theme

mkdocs/utils/__init__.py
This is a custom implementation that's significantly faster but always gives the exact same results as the current one. The use of `posixpath.relpath` pulled in several path-specific transformations that are never needed here.
Efficiency is important because calls to `normalize_url` (e.g.) on a site with ~300 pages currently take up ~10% of the total run time due to the sheer number of them. The number of calls is at least the number of pages squared.
Generally, approximating that the number of these calls is N&times;N&times;2, this is the graph that we end up with:
[Full source code how I got this result](https://gist.github.com/b7d9b1e6bbecd4415dabb70aaba4c581)
This shows the total time spent getting relative paths (Y axis) over the course of building a site with that many pages (X …
=> Optimize getting relative page URLs, now with less custom code

mkdocs/livereload/__init__.py, mkdocs/tests/livereload_tests.py
This goes back to the approach that was always used with 'livereload' library (but now just using the 'watchdog' implementation of the same), meaning the same downsides with latency and CPU usage.
But we have to do this to reasonably support usages that span virtual filesystems such as non-native Docker and network mounts.
This also simplifies the code, as the polling observer already follows symlinks and happens to support watching paths of files directly
Fixes #2457
=> Revert livereload file watching to use polling observer

docs/about/contributing.md
In https://github.com/mkdocs/mkdocs/issues/1972#issuecomment-582952604
I was pointed to the README, but I hadn't looked for contact information there.
I think looking on the website is a reasonable way, and pointing to the README
from the "Contributing" page looks like a good help to me.
=> Add link to README to contributing.md

mkdocs/commands/build.py, mkdocs/commands/serve.py, mkdocs/config/config_options.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/utils/__init__.py
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlsplit
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse
It's the same but doesn't treat ';' as a special character in paths; and I don't think anyone would expect it to be special
=> Replace urlparse with urlsplit

.github/workflows/tox.yml
This is more considerate of the computational resources. The lint checks are not the bottleneck, and now they won't starve other jobs from starting.
All checks will still run and a failure in any of them will fail the job.
Also upgrade Python and Node versions
=> CI: Run all lint checks in one job

docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
Some of the docs were accidentally reverted with other things, so I'm restoring them and adding a bit more.
Fixing an edge case: it is in fact possible to specify a URL with scheme and without netloc. Adding new tests to also catch that.
=> Tighten the docs and tests around `site_url`

mkdocs/livereload/__init__.py, mkdocs/tests/livereload_tests.py
Don't require trailing slash when serving a directory index in the livereload/local server.
Instead of showing a 404 error, detect if it's a directory and redirect to a path with a trailing slash added.
Fixes #2456
=> Don't require trailing slash when serving a directory index

docs/dev-guide/themes.md, docs/user-guide/localizing-your-theme.md
Fix whitespace added to codespan and ISO link not consistent across entire docs. Also add links that I've missed reading these parts.
=> Fix minor errors in documentation

mkdocs/themes/readthedocs/locales/es/LC_MESSAGES/messages.po
I'm not sure why these weren't added in #2396, maybe I forget to run `update_catalog` after `init_catalog`. This is the cause of the [failure ocurred in latest release workflow](https://github.com/mkdocs/mkdocs/runs/3098566096).
=> Add missing es translations to readthedocs theme

.github/workflows/tox.yml, mkdocs/themes/mkdocs/js/base.js, tox.ini
As suggested by [this comment in previous PR](https://github.com/mkdocs/mkdocs/pull/2549#issuecomment-902757777), add spelling check to lint workflow in CI.
=> Add codespell step to CI lint workflow

mkdocs/structure/files.py
I've found myself when developing plugins printing `File.src_path`, a lot of times, so I've created the reproduction method based on the same defined in `Page` class.
=> Add __repr__ method to File class

docs/user-guide/choosing-your-theme.md, mkdocs/themes/mkdocs/locales/ja/LC_MESSAGES/messages.po, mkdocs/themes/readthedocs/locales/ja/LC_MESSAGES/messages.po
I'd like to add Japanese translation for built-in themes.
- `mkdocs`
- `readthedocs`
I read the following guides for contribution before I made this PR.
- https://www.mkdocs.org/about/contributing/
- https://www.mkdocs.org/dev-guide/translations/
I tested them locally following the instruction https://www.mkdocs.org/dev-guide/translations/#testing-theme-translations and they look fine.
Please let me know if there's anything I missed. Thank you in advance!
=> Add Japanese (`ja`) translation for built-in themes

docs/dev-guide/plugins.md
closes mkdocs/mkdocs#2558 thx to @hwittenborn
=> dev guide: remove misleading usage of 'entry_point' wording

docs/dev-guide/themes.md
I followed the instruction of  [Theme Package Layout](https://www.mkdocs.org/dev-guide/themes/#package-layout) and I had got the error message:
* ERROR    -  Config value: `theme`. Error: The theme `mytheme` does not appear to have a configuration file.
=> Fix typo `mkdocs-theme.yml` (`mkdocs_theme.yml`)

docs/user-guide/deploying-your-docs.md
Warning about gh-deploy overwriting gh-pages modifications appear twice. I don't think this it intended, is it?
=> Remove duplicated sentences in docs/deploying

docs/user-guide/configuration.md, mkdocs/__main__.py, mkdocs/commands/serve.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/livereload/__init__.py, mkdocs/tests/cli_tests.py, mkdocs/tests/config/config_options_tests.py
Implements #2632
* adds a `watch` property to the `mkdocs.yaml` schema. Accepts a list of directories to watch.
* adds a `-w`/`--watch` command line option to `mkdocs serve` that can be passed multiple times
* options from `mkdocs.yaml` and CLI flags are combined
* docs updated
=> Support custom directories to watch when running mkdocs serve

.github/workflows/tox.yml
The motivation is that contributors currently have no good way to test their changes before opening a pull request.
=> Allow CI to run when pushing to a branch

mkdocs/config/config_options.py
`FilesystemObject` validates previously that `value` is a string, so it's impossible that `os.path.abspath(value)` returns a string.
Note also that `assert`s are removed if Python runs with optimizations enabled, so adding `assert`s in the source code is a bad practice:
```bash
$ python3 -O -c "assert False"
$ python3 -c "assert False"
Traceback (most recent call last):
File "<string>", line 1, in <module>
AssertionError
```
=> Drop needless assert from `FilesystemObject` config option

mkdocs/theme.py, mkdocs/themes/readthedocs/base.html, mkdocs/utils/filters.py, requirements/project-min.txt, requirements/project.txt
[`tojson` filter](https://jinja.palletsprojects.com/en/3.0.x/templates/?highlight=tojson#jinja-filters.tojson) was added to Jinja2 in v2.9 and Mkdocs uses `Jinja2>=2.10.1`, so this builtin Jinja2 filter can be used instead of the custom one currently in Mkdocs, added 6 years ago in the commit https://github.com/mkdocs/mkdocs/commit/1c252ba4bb5d3d161c6c62ca790488287a69880f, when the dependency was being pinned to `Jinja2>=2.7.1`.
This filter is HTML and JS safe, so there is no need to use the `safe` filter in Readthedocs theme. Markupsafe is only explicitly used in this filter, so dropped from `project-min.txt` and `project.txt` requirements files.
=> Reuse Jinja2 `tojson` builtin filter

mkdocs/__main__.py
As you can see in the next image, when you run `mkdocs build`, `serve`, `gh_deploy` and `new` modules commands are also imported, although they are not used:
> Created with `pyinstrument -o out.html -r html -m mkdocs -- build`
These imports add some initialization time to the build because some dependencies like `watchdog` must be initialized. This PR solves it moving the imports to their respective functions.
=> Don't import not used commands modules

mkdocs/config/__init__.py, mkdocs/tests/base.py, mkdocs/tests/plugin_tests.py, mkdocs/tests/theme_tests.py, tox.ini
While bumping the version of this package from 1.2.1 to 1.2.3 for nixpkgs
I noticed the tests started failing.
I dug around a bit found that an import was incorrect (`import localization` in `theme_tests.py`)
and `config_options` and `defaults` were missing from `mkdocs/config/__init__.py`.
=> Fix imports to get tests passing

.github/workflows/tox.yml
Github Actions now uses MacOS 11 as `macos-latest` and this version [does not includes PyPy 3.6](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#pypy). There are two options to fix this problem:
- a) Use `macos-10.15` instead of `macos-latest` in the CI. This allows to continue the testing against PyPy 3.6 (see [tests passing](https://github.com/mondeja/mkdocs/runs/4942876969?check_suite_focus=true)).
- b) Use PyPy 3.7, included in latest MacOS (see [tests passing](https://github.com/mondeja/mkdocs/actions/runs/1747596121)).
I've opted for option *b* because Python3.6 EOL has been reached some months ago and because the CI is currently using latest OS builds for Windows and Linux.
=> Fix PyPy version in MacOS CI workflow

requirements/project-min.txt
See https://github.com/pallets/jinja/issues/1585
=> Pin MarkupSafe to <= 2.0.1 in minimum requirements to test against Jinja2 v2 in CI

docs/dev-guide/themes.md
It seems a mistake from #1418. JSON search indexes contains a `"docs"` object instead of one named `"data"`.
=> Fix documentation error in Developing Themes page

mkdocs/commands/serve.py
=> Make Jinja2 errors and OSErrors produce a clearer message

docs/user-guide/choosing-your-theme.md, mkdocs/themes/mkdocs/locales/fa/LC_MESSAGES/messages.po, mkdocs/themes/readthedocs/locales/fa/LC_MESSAGES/messages.po
**Changes:**
- The Persian translation has been added to `mkdocs` and `readthedocs` themes.
- The `Choosing your theme` documentation has been updated to reflect the changes.
=> Add Persian (fa) translation to the default themes.

mkdocs/config/config_options.py
=> SubConfig now catches failures and warnings

mkdocs/livereload/__init__.py, mkdocs/tests/livereload_tests.py
Previously there was a pull request "Move livereload endpoint under the mount path (#2740)"
and it definitely makes sense as a way to make livereload work behind a proxy.
However, this change also caused a major annoyance when working on several different sites.
Steps to reproduce:
1. `serve` one site (needs to have `site_url` customized)
2. open the site in a browser
3. stop serving it but keep the browser
4. `serve` another site with a different mount point
5. observe spam of "404" errors in the new terminal (also in the old browser but that's whatever)
So, this reverts the observable effect of commit fafdcc240e0520e34ac30b4dcf78adc4514101ec by @robertaistleitner
=> Revert to disregarding the mount path for /livereload/ endpoint

mkdocs/structure/files.py, mkdocs/tests/structure/file_tests.py
closes #2846
If both `README.md` and `readme.md` are present, `readme.md` is skipped.
=> Check for uppercase readme only

mkdocs/__main__.py
(previously they were not shown at all)
This works for both extensions and plugins -- and for MkDocs itself.
It will enable plugin developers to see warnings in advance. Or users to report such warnings to plugin developers.
Ref #2892, https://github.com/Python-Markdown/markdown/issues/1277
Example session:
```console
$ .venv/bin/pip install 'mdx_gh_links==0.2' 'Markdown==3.3.7'
$ PYTHONPATH=. .venv/bin/mkdocs serve                        
INFO     -  Building documentation...
INFO     -  DeprecationWarning: 'etree' is deprecated. Use 'xml.etree.ElementTree' instead.
File "/home/blaxpirit/repos/mkdocs/.venv/lib/python3.10/site-packages/mdx_gh_links.py", line 35, in <module>
from markdown.util import etree
File "/home/blaxpirit/repos/mkdocs/.venv/lib/python3.10/site-packages/markdown/util.p …
```
=> Show DeprecationWarnings as INFO messages

docs/user-guide/writing-your-docs.md, mkdocs/contrib/search/templates/search/lunr.js, mkdocs/utils/meta.py
There are small typos in:
- docs/user-guide/writing-your-docs.md
- mkdocs/contrib/search/templates/search/lunr.js
- mkdocs/utils/meta.py
Fixes:
- Should read `delimiters` rather than `deliminators`.
- Should read `environments` rather than `enviroments`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

mkdocs/structure/files.py, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
[(I also searched across GitHub that nobody uses these)](https://cs.github.com/?q=%2F\bis_html_file\b%2F+mkdocs+path%3A%2Fpy%24%2F+NOT+path%3A%2Fmkdocs\%2F(utils|build|nav|test|relative_path_ext|config)%2F)
For `is_markdown_file` instead do a breaking change so it matches the actual behavior of MkDocs build: don't accept uppercase extensions anymore.
=> Simplify utils, deprecate unused functions

.github/workflows/tox.yml
This check has only caused a lot of spurious failures. I never check it. In my view this approach is still a non-starter, and my comments had predicted the problems quite spot-on: https://github.com/mkdocs/mkdocs/pull/2299#issuecomment-804362611
=> CI: stop checking diffs in translation files

mkdocs/tests/config/config_options_tests.py, mkdocs/tests/config/config_tests.py, mkdocs/tests/search_tests.py, mkdocs/tests/structure/file_tests.py, mkdocs/tests/structure/page_tests.py, mkdocs/tests/utils/utils_tests.py
This allows finding which of the cases failed, otherwise the error just points to the line number.
=> Refactor tests to use `subTest`

docs/css/extra.css, docs/dev-guide/plugins.md, mkdocs.yml, mkdocs/plugins.py, mkdocs/tests/plugin_tests.py, requirements/project-min.txt, requirements/project.txt, requirements/test.txt, tox.ini
- Move plugin events docs into source code + refactor
* Create real (no-op) methods for each event in the base class.
* Refactor event dispatcher to not check for methods' existence, instead just call them.
* Move documentation from Markdown into docstrings of these methods.
* Activate the 'mkdocstrings' plugin.
* Use 'mkdocstrings' to insert documentation from those docstrings into the site.
- Add type annotations for plugin events, include them in the docs
- Drop py36 integration tests because mkdocstrings is >=3.7
=> Refactor plugin events, move docs to source code, type annotations

mkdocs/commands/build.py, mkdocs/structure/files.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/tests/base.py, mkdocs/tests/build_tests.py, mkdocs/tests/structure/file_tests.py, mkdocs/tests/structure/page_tests.py, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
The only breaking change is supposed to be that in some cases `\` will no longer be converted to `/` - that behavior will be exclusive to Windows.
=> Refactor URI handling to not have to deal with backslashes

mkdocs/plugins.py, mkdocs/tests/plugin_tests.py
See prior: https://github.com/mkdocs/mkdocs/commit/f79b34d174e41084391868e7b503f5c61b8b1bdf#diff-da2086192f0b49a8ae9a67eba6ec5e7572aaa0c0db458b1d9deea21005fc7655L84
But now we need to also skip non-overridden methods. That's also the reason why I needed to use `staticmethod`, so these are not concealed by `bound method` functionality.
=> Revert to the explicit way of registering plugins' methods

README.md
Following the advice of @squidfunk, I'm opening this PR to get feedback from MkDocs maintainers and open a discussion :slightly_smiling_face: 
This PR adds a link to the [best-of-mkdocs](https://github.com/pawamoy/best-of-mkdocs) list I've just created to the README.
Providing such curated data / galleries of examples in MkDocs own docs has been discussed previously in #2700.
I wouldn't mind transferring the best-of list to the MkDocs org and keep maintaining it, if that's something you'd like (it's pretty low maintenance as the only file to update is the YAML data, the rest is automatically rendered through a GitHub action).
One of the benefits of the best-of list is that it logs useful information during the rendering process. For example, I was able to fix several plugins URLs as they …
=> Add a link to best-of-mkdocs in the readme

.github/workflows/tox.yml
Let's save computational resources and also not get throttled as much while we're at it
=> Slim down the CI test matrix

mkdocs/plugins.py, mkdocs/structure/nav.py, mkdocs/tests/plugin_tests.py
Another followup to #2937
mypy requires the methods to be non-static to be able to understand their overrides.
I just didn't want to deal with the `<bound method ...>` stuff and had to make them static previously. Instead now I actually delete all those methods right after defining them. The trick passes for both mkdocstrings and mypy
=> Change back to non-static event methods, but delete the defs

docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/structure/pages.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/structure/page_tests.py
=> Add `edit_uri_template` config

docs/css/extra.css, docs/dev-guide/plugins.md, mkdocs/plugins.py, mkdocs/tests/plugin_tests.py, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
Add a decorator that sets a priority value for plugins' events.
Events with higher priority are called first.
Events without a chosen priority get a default of 0.
Events that have the same priority are ordered as they appear in the config.
Recommended priority values:
`100` "first", `50` "early", `0` "default", `-50` "late", `-100` "last".
As different plugins discover more precise relations to each other, the values should be further tweaked.
```python
@plugins.event_priority(-100)  # Wishing to run this after all other plugins' `on_files` events.
def on_files(self, files, config, **kwargs):
...
```
=> Let plugins choose the priority order of their events

docs/css/extra.css, docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/plugins.py, mkdocs/tests/config/config_options_tests.py
Add a new `hooks` config to `mkdocs.yml`:
A list of paths to Python scripts (relative to `mkdocs.yml`) that are loaded and used as [plugin](https://www.mkdocs.org/dev-guide/plugins/) instances.
For example:
```yaml
hooks:
- my_hooks.py
```
Then the file *my_hooks.py* can contain any [plugin event handlers](https://www.mkdocs.org/dev-guide/plugins/#events) (without `self`), e.g.:
```python
def on_page_markdown(markdown, **kwargs):
return markdown.replace('a', 'z')
```
This does not enable any new abilities compared to plugins, it only simplifies one-off usages, as these don't need to be *installed* like plugins do.
Note that for `mkdocs serve` the hook module will *not* be reloaded on each build.
You might have seen this feature in the [mkdocs-simple-hooks …
=> Hooks feature: run plugin events from local Python files

docs/css/extra.css, docs/dev-guide/plugins.md, mkdocs/themes/mkdocs/css/base.css
* Apply admonition styles also to `<details>` tags
* Remove extraneous margin at the bottom of admonition blocks
* Increase contrast of default admonitions
* Add some admonition styles (only for use on MkDocs' site for now)
=> Update admonition styles in MkDocs theme

.markdownlintrc, docs/about/release-notes.md, docs/css/extra.css, docs/dev-guide/plugins.md, docs/dev-guide/themes.md, docs/getting-started.md, docs/user-guide/choosing-your-theme.md, docs/user-guide/configuration.md, docs/user-guide/customizing-your-theme.md, docs/user-guide/deploying-your-docs.md, docs/user-guide/installation.md, docs/user-guide/writing-your-docs.md, mkdocs.yml, requirements/project-min.txt, requirements/project.txt
- Enable `<details>` admonitions and nested codeblocks
- Enforce fenced codeblocks in our docs
- Replace instances of ```no-highlight
=> Docs: update Markdown style

mkdocs/tests/build_tests.py, mkdocs/tests/utils/utils_tests.py, mkdocs/utils/__init__.py
=> Revert dropping support for backslashes in media URIs

mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/contrib/search/__init__.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/config/config_tests.py, mkdocs/tests/plugin_tests.py
* Refactor: use config_options module through a short alias 'c' 
* Refactor config_option_tests to be more consistent
* Soft-deprecate ConfigItems instead of expanding it
This undoes the addition of the `validate` parameter from ee844242d11c028e2eea3c07e468b36f1a45b68a.
It is OK to do because this was not released yet.
=> Refactor in preparation for ConfigOption schemas rework

docs/user-guide/README.md, docs/user-guide/cli.md, mkdocs.yml, pyproject.toml
Preview: https://oprypin.github.io/mkdocs/user-guide/cli/
Closes #837
=> Add CLI reference page, auto-generated from Click

mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/plugins.py, mkdocs/tests/config/config_options_legacy_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/plugin_tests.py
- Refactor Theme config option to use mainly run_validation
- Expand plugin testing
- Tighten warnings and type annotations in config_options
- Refactor plugin_cache usage to avoid nested exception
- Also tighten warnings of plugin configs
- Refactor `load_plugin` usage
- Better guard an edge case in plugin config
=> Refactor plugin-related config options and error reporting

mkdocs/livereload/__init__.py, mkdocs/tests/livereload_tests.py
When the `site_url` contains utf-8 characters (e.g. http://fake.domain/測試) and uses `mkdocs server` to serve doc, visiting localhost:8000 will cause wsgi encoding error when doing 302 redirects. The error log is as follows:
```
Traceback (most recent call last):
File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 138, in run
self.finish_response()
File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 185, in finish_response
self.finish_content()
File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 324, in finish_content
self.send_headers()
File …
```
=> URL-encode paths when serving a redirect

mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_options_legacy_tests.py, mkdocs/tests/config/config_options_tests.py
- Let plugins put strings into `warnings`
Fixes #3014
- Reduce redundancy in config errors/warnings
=> Update warnings of config options

mkdocs/config/config_options.py, mkdocs/plugins.py, mkdocs/tests/config/config_options_tests.py
* Addresses https://github.com/squidfunk/mkdocs-material/issues/4542
E.g.:
```yaml
plugins:
- blog:
blog_dir: blog
- blog:
blog_dir: tutorial
```
Depending on what a plugin does, say if it "adds a thing" into the site, it can be reasonable to allow it to be specified multiple times in the `plugins:` list, so it can "add multiple things". Previously such a use case was completely not predicted in MkDocs, so it silently passes but is bugged - the plugin runs twice but with only one of the configs both times.
So, this PR addresses that by registering a plugin `- foo:` as `'foo'`, and then if another plugin `- foo:` appears, it gets registered as `'foo #2'` (the name affects primarily just how it's referred to in warnings and errors).
By default, a warning will appear from MkDocs anyway, …
=> Support multiple instances of the same plugin

docs/dev-guide/plugins.md
> **Note**: This is a trivial typo, please see file changes for details.
The example was introduced in #2962. ([a4c1bb](https://github.com/mkdocs/mkdocs/commit/a4c1bb14dc42457a96ecaf11e450845d0c2d1dfe#diff-62543f71a205c3af3b9d2c99760cd073ac9b9dce3baaf0e66bbcebe651a59eedR173-R177) to be specific)
No idea why it wasn't aligned.
=> [Docs] Fix indents in the example code

docs/index.md, docs/user-guide/writing-your-docs.md, mkdocs/commands/gh_deploy.py
To be consistent with GitHub's usage, and the use in MkDocs' documentation elsewhere.
=> Correct capitalisation of "GitHub Pages"

mkdocs/config/config_options.py
=> Add hooks to `sys.modules` because some Python features rely on this

mkdocs/themes/readthedocs/breadcrumbs.html
Fixes #2827.
This fix matches the change in the upstream ReadTheDocs theme by replacing an A tag's invalid "alt" attribute with an "aria-label" attribute that screen readers can consume.
=> Fix accessibility issue with top-level breadcrumb in ReadTheDocs theme

mkdocs/themes/readthedocs/search.html, mkdocs/themes/readthedocs/searchbox.html
=> Adding search input field labels using aria-label

README.md, docs/dev-guide/plugins.md, docs/dev-guide/themes.md, docs/index.md, docs/user-guide/choosing-your-theme.md, docs/user-guide/configuration.md
* From https://github.com/mkdocs/mkdocs/discussions/2823
https://github.com/mkdocs/best-of-mkdocs
=> Link to Best-of-MkDocs instead of Plugins wiki in docs

mkdocs/commands/build.py, mkdocs/commands/gh_deploy.py, mkdocs/commands/serve.py, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/contrib/search/__init__.py, mkdocs/contrib/search/search_index.py, mkdocs/livereload/__init__.py, mkdocs/localization.py, mkdocs/plugins.py, mkdocs/structure/files.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/structure/toc.py, mkdocs/tests/base.py, mkdocs/tests/config/config_options_legacy_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/plugin_tests.py, mkdocs/theme.py, mkdocs/utils/__init__.py, mkdocs/utils/meta.py
* https://peps.python.org/pep-0563/ - Postponed Evaluation of Annotations
* https://peps.python.org/pep-0585/ - Type Hinting Generics In Standard Collections
* https://peps.python.org/pep-0604/ - Allow writing union types as `X | Y`
=> Modernize type annotations using `pyupgrade`

pyproject.toml
* Closes #3214
* Reverts #2893
Perhaps it is time to let the hell break loose in the next release. A few projects probably still remain broken with the new version of Markdown, but this indiscriminate pinning might even be the worse tradeoff.
=> Un-pin upper version of Python-Markdown

.flake8, mkdocs/commands/build.py, mkdocs/commands/gh_deploy.py, mkdocs/commands/serve.py, mkdocs/config/config_options.py, mkdocs/contrib/search/__init__.py, mkdocs/contrib/search/search_index.py, mkdocs/plugins.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, pyproject.toml
I realized that actually `livereload` gets imported even as part of `mkdocs build`, this prevents it.
Ref https://github.com/mkdocs/mkdocs/pull/3219#issuecomment-1545960511 @pawamoy
=> Enforce that imports are under `if TYPE_CHECKING` if possible

docs/css/extra.css
I've updated mkdocstrings' Python handler, and while checking the docs for MkDocs I noticed these labels were displayed. Since you already hide `class-attribute` labels, I figured you'd like to hide these ones as well.
=> Hide instance-attribute labels in docs

mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
As discussed in https://github.com/mkdocs/mkdocs/discussions/3240.
Absolutely feel free to push to the branch directly.
I copied the tests for `ListOfItems` and adapted them.
=> Add `DictOfItems` type for configuration options

.flake8, docs/user-guide/configuration.md, docs/user-guide/writing-your-docs.md, mkdocs/__main__.py, mkdocs/commands/build.py, mkdocs/commands/serve.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/livereload/__init__.py, mkdocs/plugins.py, mkdocs/structure/files.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/tests/base.py, mkdocs/tests/build_tests.py, mkdocs/tests/cli_tests.py, mkdocs/tests/livereload_tests.py, mkdocs/tests/plugin_tests.py, mkdocs/tests/search_tests.py, mkdocs/tests/structure/file_tests.py, mkdocs/tests/structure/nav_tests.py, mkdocs/utils/__init__.py, pyproject.toml
These files will not be picked up into the `Files` collection and as such, also the final built site.
Also adds the ability to *un*-ignore the files that MkDocs forcibly ignores.
* Closes #2139
* Closes #2316
* Closes #2185
* Closes #1888
* Closes #3110
=> New `exclude_docs` config: gitignore-like patterns of files to exclude

mkdocs/config/base.py, mkdocs/localization.py, mkdocs/tests/__init__.py, mkdocs/tests/config/config_options_tests.py, mkdocs/theme.py
- Deprecate `user_configs`
- Deprecate `Theme._vars` but add `custom_dir` and other attributes
=> Deprecate Theme-related fields that were accidentally available

docs/dev-guide/api.md, docs/dev-guide/themes.md, docs/user-guide/configuration.md, docs/user-guide/customizing-your-theme.md, mkdocs/commands/build.py, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/contrib/search/__init__.py, mkdocs/livereload/__init__.py, mkdocs/plugins.py, mkdocs/structure/files.py, mkdocs/tests/config/config_options_legacy_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/utils/templates_tests.py, mkdocs/theme.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/readthedocs/base.html, mkdocs/utils/__init__.py, mkdocs/utils/filters.py, mkdocs/utils/templates.py, pyproject.toml
* Closes #2850
* Closes #1581
* Closes #3164
* Closes #3232
---
See docs [in the diff](https://github.com/mkdocs/mkdocs/pull/3237/files).
Try it out:
```
pip install git+https://github.com/mkdocs/mkdocs.git@refs/pull/3237/head
```
Particularly I'm hoping the frontend change of fiddling with `defer` in standard themes doesn't cause problems.
---
Frontend changes:
- Stop using `defer` for all scripts
- Update highlight.js to version 11.8.0
Small config features:
- Fix propagating warnings from sub-items of `ListOfItems`
- Strip trailing `_` from config members, to bypass Python reserved words
- Make it possible to create a subclass of `SubConfig[T]`
Refactors:
- Consistently use `tojson` for pasting strings to JavaScript
- More concise error message in `SubConfig`
- Make `TemplateContext` …
=> Support `<script type="module">` and other attributes

docs/dev-guide/themes.md, docs/user-guide/configuration.md, mkdocs/__main__.py, mkdocs/commands/build.py, mkdocs/commands/gh_deploy.py, mkdocs/commands/serve.py, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/plugins.py, mkdocs/structure/__init__.py, mkdocs/structure/files.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/tests/base.py, mkdocs/tests/config/config_tests.py, mkdocs/tests/plugin_tests.py, mkdocs/themes/mkdocs/base.html, mkdocs/themes/readthedocs/base.html
- Properly support `config_file_path` being None
closes #1499
- Stricter type annotations for `MkDocsConfig`
- Define a base class for all navigation item classes
-  Use type-safe wrappers around `run_event`
=> More precise types; support stdin as the `--config-file`

mkdocs/config/config_options.py, mkdocs/tests/config/config_options_legacy_tests.py, mkdocs/tests/config/config_options_tests.py
This ensures FilesystemObject fields in Config are correctly evaluated relative to mkdocs.yaml.
See #3264
=> Pass config file path through SubConfig to Config

docs/dev-guide/plugins.md, docs/hooks.py, docs/user-guide/configuration.md, mkdocs/commands/build.py, mkdocs/commands/gh_deploy.py, mkdocs/commands/serve.py, mkdocs/config/base.py, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/tests/build_tests.py, mkdocs/utils/__init__.py, mkdocs/utils/yaml.py
* Closes #2154
```yaml
- !relative  # Obtains the directory of the currently rendered Markdown file
- !relative $config_dir  # Obtains the directory of mkdocs.yml
- !relative $docs_dir  # Obtains the docs_dir
- !relative $docs_dir/some/child/dir
```
=> Add YAML placeholder tags that resolve to current paths

docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/tests/build_tests.py, mkdocs/tests/config/base_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/search_tests.py, mkdocs/tests/structure/nav_tests.py, mkdocs/tests/structure/page_tests.py, mkdocs/utils/__init__.py
* Expand the situations where logs about broken links are produced, make the logging levels fully configurable
* Guess what existing page might have been meant based on the provided link, and mention it in the log message.
Closes #1755 and a lot more
=> Expand link validation, add configs for it

mkdocs/themes/mkdocs/css/base.css
Style before: literally just a normal paragraph
Style after:
=> Add blockquote styling for mkdocs theme

mkdocs/structure/files.py, mkdocs/structure/pages.py, mkdocs/tests/structure/page_tests.py, pyproject.toml
- Always set `inclusion_level` so static-i18n plugin keeps working
- Fix unescaping of Markdown titles
- Add a test for relative link without dot in filename
Found in https://github.com/mkdocs/regressions/actions/runs/5591321689
=> Regression fixes

mkdocs/structure/files.py
Fixes #3313
This PR catches `ValueError` to improve the safety of the `list.remove` calls, as they may attempt to remove the same file multiple times.
I think this is more acceptable than...
```python
if a in files: files.remove(a)
```
... because files can be a really large list to iterate across.
=> Catch ValueErrors thrown when attempting to remove a file twice

mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
In 1.5.0 `extra_javascript` was changed to become a `list[ExtraScriptValue]`, but strings could sneak in anyway, although MkDocs would never put them there anymore.
Let's change it to officially be `list[ExtraScriptValue | str]` but typically these items will be strings once again, unless specified as a dictionary in the config in the first place. This will guard plugins that aren't updated yet from a breakages unless users actually use `mjs` files.
* Fixes #3321, #3310
=> Change extra_javascript items to usually be strings again

mkdocs/structure/nav.py, mkdocs/structure/pages.py
I'm currently rewriting the [blog plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#built-in-blog-plugin) in Material for MkDocs (which is now free as part of the community edition), trying to improve interop with the plugin ecosystem, specifically plugins like awesome-pages or static-i18n. For this, I'm subclassing some of the existing classes. However, when we print `nav` for debugging, the names of the subclasses are not taken into account. This PR improves debug output when subclassing `Page`, `Link` or `Section` classes, which is especially useful for understanding navigation structure.
In this example, `Archive` and `Category` are subclasses of `Page`:
```
Section(title='Blog')
Page(title=[blank], url='/blog/')
Page(title=[blank], url='/blog/about/') …
```
=> Improve debug output for subclasses of navigation elements

mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
This happens because the `theme` option fails validation (being not installed) but then validation of `plugins` option fatally fails because that option is invalid. Maybe in the future it would be better to change validation so it stops after the first error, because there can be countless such combinations of interactions.
=> Prevent a stacktrace for `theme: foo` when theme is not installed

mkdocs/structure/nav.py, mkdocs/tests/structure/nav_tests.py
=> Allow plugins to provide their own `Page`

mkdocs/themes/readthedocs/breadcrumbs.html
- Fix broken styling of breadcrumbs in readthedocs theme
Commit https://github.com/mkdocs/mkdocs/commit/3c3670d92c972d874d7fe927df5abf728e003a66 left it half way between the old and new style
Fixes #3382
- Fix linkified breadcrumb items in readthedocs theme
A doc can never have a `link` attribute so this branch never kicked in.
Actually even now, this branch will still not kick in, only mkdocs-section-index makes this state possible.
=> Fix breadcrumb display in readthedocs theme

mkdocs/livereload/__init__.py
Closes #3389 and supersedes/closes #3390.
I've refactored the livereload functionality. It's more predictable now and solves another problem: it's currently not possible to open more than 6 tabs, because browsers are limited to 10 connections per destination, and the livereload connections queue up and block further connections. The problem is that every tab will keep an active livereload connection, regardless of whether it is visible or not.
This makes working on several pages in parallel impossible – see the never ending loading indicators here:
This PR addresses this issue and makes livereload more efficient.
1. Logic is refactored into two functions, `poll` and `stop`, that are called when certain events happen
2. The livereload server connection is cancelled when the tab becomes …
=> Improve editing experience when using `--livereload`

mkdocs/themes/readthedocs/versions.html
If a repo was defined for the readthedocs theme, but the repo wasn't a predefined provider (GitHub, Bitbucket, or GitLab), no repo link would be rendered.
This adds a fallback generic git repo link.
Fixes #3259
=> Add fallback git link for non-provider repos

mkdocs/config/base.py
If one config option completely fails validation, that means its value remains "raw" from YAML, which can cause unpredictable errors when validating other options that might look at the value. Instead just decide one error is enough.
* See one such case: https://github.com/mkdocs/mkdocs/pull/3351
=> Stop config validation after the first error

mkdocs/plugins.py
=> In verbose log, report each plugin's events individually

docs/user-guide/configuration.md, mkdocs/commands/build.py, mkdocs/structure/files.py, mkdocs/structure/nav.py, mkdocs/tests/structure/nav_tests.py
- Error when setting File.page to a type other than Page
As per the prior plan https://github.com/mkdocs/mkdocs/pull/3381#issuecomment-1712750515
- When `nav` config is not specified, apply file inclusion
to decide whether a file in included when generating the implicit nav.
Fixes https://github.com/mkdocs/mkdocs/issues/3336
=> Apply planned changes to `File.page` and `not_in_nav`

docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/tests/config/config_options_tests.py
For every plugin, the user can set `enabled: false` (or something based on an environment variable) and it will not kick in at all.
If the plugin has its own `enabled` config, there's no change for it in that case.
* Closes #3386
=> Add an `enabled` setting for all plugins

mkdocs/commands/serve.py
This was aimed at user-facing "file not found" errors from "serve" but it can catch errors from plugins as well, and it only makes the errors very confusing.
=> Stop suppressing OSError indiscriminately during build

docs/about/contributing.md, docs/about/release-notes.md, docs/dev-guide/themes.md, docs/dev-guide/translations.md, docs/user-guide/localizing-your-theme.md
This is strictly necessary when using non-bash shells (e.g. tcsh).
=> Quoted pip arguments containing square brackets

docs/dev-guide/plugins.md, mkdocs/plugins.py, mkdocs/tests/plugin_tests.py
=> Allow adding event handlers at multiple priorities

mkdocs/config/config_options.py, mkdocs/tests/build_tests.py, mkdocs/utils/yaml.py
If a Markdown extension immediately resolves the path inside its initialization (rather than just storing it for later as I was hoping) then it was failing the initial validation run that MkDocs does without populating an actual page yet.
* Fixes #3453
=> Fix overzealous validation of `!relative` tag

docs/dev-guide/plugins.md, docs/user-guide/choosing-your-theme.md, mkdocs/tests/theme_tests.py, mkdocs/tests/utils/utils_tests.py, mkdocs/theme.py, mkdocs/utils/__init__.py
@jorgectf 
This is the outcome of https://github.com/mkdocs/mkdocs/issues/3418
Which warned about arbitrary code execution via installing a theme and that theme having malicious YAML tags.
I found that there are a lot more ways for arbitrary code execution if you install an untrusted package and import it.
As such, this change only slightly reduces the attack surface, but at the same time I don't really consider it a security issue in the first place, and I don't think it'd be useful for users to see all versions of MkDocs as having a security vulnerability and then also see that this change fixes it (but actually not really).
But I agree:
* executing YAML tags in `mkdocs_theme.yml` *is* pointless.
* the documentation *could* definitely use a note about the dangers of third-party …
=> Stop executing YAML tags for mkdocs_theme.yml, warn about third-party projects

mkdocs/__main__.py, mkdocs/commands/serve.py, mkdocs/livereload/__init__.py, mkdocs/tests/cli_tests.py
After the first build is finished, the default webbrowser will open the home page of the site.
Third take! Let's just solve this feature separately.
* Closes #3495
=> New flag `serve --open` to open the site in a browser

mkdocs/commands/build.py, mkdocs/structure/pages.py, mkdocs/tests/build_tests.py, mkdocs/utils/__init__.py
The gzip format stores a timestamp inside it, but there's no real point to it being correct.
If a site is rebuilt exactly the same twice, the timestamp *metadata* of files will be different sure, but this gzip file was the only one that also had *actual content* that is different each time.
Now instead the date of the gzip file will change only once per day, based on the pages' update date. The sitemap.xml itself also changes once per day already.
* Closes #2689
=> Make sitemap.xml.gz slightly more reproducible

.markdownlintrc, docs/about/release-notes.md, docs/dev-guide/plugins.md, docs/dev-guide/themes.md, docs/user-guide/configuration.md, mkdocs/__main__.py, mkdocs/commands/build.py, mkdocs/config/defaults.py, mkdocs/structure/files.py, mkdocs/structure/pages.py, mkdocs/tests/build_tests.py, mkdocs/tests/cli_tests.py, mkdocs/tests/config/config_options_tests.py, mkdocs/tests/structure/file_tests.py, mkdocs/tests/structure/page_tests.py
Example message:
WARNING -  Doc file 'dev-guide/themes.md' contains a link '../user-guide/configuration.md#google_analytics', but the doc 'user-guide/configuration.md' does not contain an anchor '#google>
It is not enabled by default. To increase to warning level, use config `validation: {anchors: warn}`
The implementation only detects Markdown anchors, not raw HTML anchors. As such it may have false positives.
~~The implementation now detects both Markdown anchors and raw HTML anchors~~
```markdown
<a id="undetectable-anchor"></a>
```
But that's just about user-authored HTML.
As for HTML that Markdown extensions insert: it will also work correctly if they insert the HTML as etree elements and will never work if they insert it via `htmlStash`. Basically the same rules as for what …
=> Implement validation of anchors in links to other pages

docs/user-guide/configuration.md, mkdocs/config/config_options.py, mkdocs/config/defaults.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/tests/structure/nav_tests.py, mkdocs/tests/structure/page_tests.py
Add a new config option:
```yaml
validation:
links:
absolute_links: relative_to_docs
```
This makes absolute links be validated relative to docs_dir and be turned into relative links.
* Closes #1592
* Closes #3308
=> Validation of absolute links relative to docs root

docs/getting-started.md
The Getting started page mentions `site_url` being a required option. This can't be true however, since making a new MkDocs project using `mkdocs new` only generates a `mkdocs.yml` file containing the `site_name` option, which works fine when using the serve and build commands, meaning site_url is optional.
This is further confirmed by the fact that the Configuration page mentions that only site_name is required and all other options being optional.
This PR removes the `site_url: https://example.com/` from the code snippets while also updating the NOTE box about this option being required, by removing it altogether.
=> Remove mention of site_url being required option

mkdocs/commands/build.py, mkdocs/plugins.py, mkdocs/structure/files.py, mkdocs/structure/nav.py, mkdocs/structure/pages.py, mkdocs/tests/build_tests.py, mkdocs/tests/structure/file_tests.py, mkdocs/tests/structure/page_tests.py
=> Rework Files to support generated files

.github/workflows/autofix.yml, .github/workflows/ci.yml, pyproject.toml
If a pull request has applicable Ruff fixes or needs re-formatting with Black/isort, these will be automatically pushed to the pull request via https://pre-commit.ci/lite.html
Versions of these formatter tools are already pinned since commit c9cf11b94172b9cf851e29c535def8667891b65c, so unexpected unrelated changes from just updating these tools will not happen.
Note that the actual pre-commit tool is not used, and there are no plans for that.
---
See how it looks: https://github.com/oprypin/mkdocs/pull/3
=> Set up automatic fixes for PRs using pre-commit-ci-lite

mkdocs/themes/mkdocs/locales/pl/LC_MESSAGES/messages.po, mkdocs/themes/readthedocs/footer.html, mkdocs/themes/readthedocs/locales/pl/LC_MESSAGES/messages.po, mkdocs/themes/readthedocs/messages.pot
Hello, I added `.po` files with Polish language strings for the two built-in themes.
Unfortunately, lunr-languages doesn't support Polish but I think this is out of scope for this pull request.
I also noticed that in the "ReadTheDocs" theme, in the footer the word "theme" is not added as a translatable string:
> Built with [MkDocs](https://www.mkdocs.org/) using a [theme](https://github.com/readthedocs/sphinx_rtd_theme) provided by [Read the Docs](https://readthedocs.org/).
Therefore it gets translated to:
> Zbudowano przy użyciu [MkDocs](https://www.mkdocs.org/) z pomocą [theme](https://github.com/readthedocs/sphinx_rtd_theme) dostarczonego przez [Read the Docs](https://readthedocs.org/).
Would it be OK to modify `footer.html` within this PR so that the word "theme" gets added to …
=> Add Polish translation for built-in themes

mkdocs/config/base.py
In certain constrained environments, stdin will not be defined:
```shell
bash -c $'0>&- python -c \'import sys; print(f"stdin: {sys.stdin}")\''
stdin: None
```
An example of this could be a CI or Deployments environment.
=> stdin is not guaranteed to be defined

mkdocs/themes/mkdocs/base.html
This needed to be updated when upgrading the mkdocs theme to newer Bootstrap but got missed.
Only one branch was updated https://github.com/mkdocs/mkdocs/commit/694a6028f649de6881ddc13496077856dcb3abc6#diff-d1c13966984c4c14f25c9d8ee66694e694dd9c4756a6d706fbc20135ff4ba3dcR142
Right now it shows up as a missing glyph.
=> Fix for showing repository icon even when a file has no edit_uri

mkdocs/templates/sitemap.xml
Closes #3516.
In brief...
> I've noticed that in the sitemap.xml template file [...], the tag is hard-coded to "daily"
> I'd vouch for removing changefreq altogether. It's optional anyway, and I doubt that any of the big relevant search engines will use it when deciding when to re-index your site
Seems like a reasonable tweak to me.
Should this pull request also update the [release notes](https://github.com/mkdocs/mkdocs/blob/master/docs/about/release-notes.md) or are we waiting until we push a release before we collate those?
=> Drop `changefreq` from `sitemap.xml`.

docs/user-guide/deploying-your-docs.md
This commit updates the documentation about "Read the Docs":
- removes unsupported version control systems; only Git is supported now (see https://about.readthedocs.com/blog/2024/02/drop-support-for-subversion-mercurial-bazaar/)
- removes the note mentioning that not all the features are supported with other MkDocs themes since this is not valid anymore
Closes #3579
=> Docs: update "Read the Docs hosting"

mkdocs/tests/theme_tests.py, mkdocs/theme.py
=> Fix crash when mkdocs_theme.yml is empty

pyproject.toml
Fixes including #3729 and #3730 are currently blocked on CI failures.
Failure is due to https://github.com/codespell-project/codespell/issues/3430
Attempt to resolve this by pining the codespell [to the previous release](https://pypi.org/project/codespell/#history).
Really I'd like us to switch to a simpler CI workflow, tho let's deal with the immediate issue first.
=> Pin codespell dependancie

mkdocs/config/config_options.py, mkdocs/tests/config/config_options_legacy_tests.py, mkdocs/tests/config/config_options_tests.py
Fixes #3724 and #2108. Consensus for this change was reached in https://github.com/mkdocs/mkdocs/issues/3724#issuecomment-2178996420
> I'd suggest we simply don't enforce the check against 0.0.0.0. (https://github.com/mkdocs/mkdocs/pull/2022)
Less config is better. Less code is better.
=> Fix strict mode in Docker by removing 0.0.0.0 warning

mkdocs/__main__.py
=> Allow controlling Python warnings with `python -W` and `PYTHONWARNINGS` again

mkdocs/utils/__init__.py
Closes #3794 
Not clear to me if...
* There may also be a timezone issue here leading to the negative value.
And furthermore...
* Non-integer values will still raise an exception here.
But this does at least resolve the immediate issue.
Thanks to @vedranmiletic for raising the issue and @pawamoy for the confimation.
=> Resolve `SOURCE_DATE_EPOCH=0` bug.

docs/about/release-notes.md, mkdocs/__init__.py
Release notes for this version...
---
* Fix build error when environment variable `SOURCE_DATE_EPOCH=0` is set. #3795
* Fix build error when `mkdocs_theme.yml` config is empty. #3700
* Support `python -W` and `PYTHONWARNINGS` instead of overriding the configuration. #3809
* Support running with Docker under strict mode, by removing `0.0.0.0` dev server warning. #3784
* Drop unnecessary `changefreq` from `sitemap.xml`. #3629
* Fix JavaScript console error when closing menu dropdown. #3774
* Fix JavaScript console error that occur on repeated clicks. #3730
* Fix JavaScript console error that can occur on dropdown selections. #3694
* Added translations for Dutch. #3804
* Added and updated translations for Chinese (Simplified). #3684
---
Note that the release notes do not include …
=> Version 1.6.1.

docs/user-guide/configuration.md, mkdocs/tests/__init__.py, mkdocs/tests/build_tests.py
Update the User Guide descriptions that use inline comments in gitignore syntax (which doesn't work), and add a test that the mult-iline `draft_docs` definition replacement does work correctly.
Fixes  #3858
=> fix and test description of draft_docs
