mkdocs/build.py
mkdocs/config.py
mkdocs/main.py
mkdocs/test.py

We log an error about the missing file, and skip building of that page

Fix #164: serve ignores missing files

---

mkdocs/config.py

Fix hostname for BitBucket

---

mkdocs/themes/amelia/base.html
mkdocs/themes/bootstrap/base.html
mkdocs/themes/cerulean/base.html
mkdocs/themes/cosmo/base.html
mkdocs/themes/cyborg/base.html
mkdocs/themes/flatly/base.html
mkdocs/themes/journal/base.html
mkdocs/themes/readable/base.html
mkdocs/themes/readthedocs/base.html
mkdocs/themes/simplex/base.html
mkdocs/themes/slate/base.html
mkdocs/themes/spacelab/base.html
mkdocs/themes/united/base.html
mkdocs/themes/yeti/base.html

Copy+paste google_analytics block to all base.html files.
Fixes #333

Add Google Analytics block to all themes

---

mkdocs/themes/bootstrap/base.html

Add copyright notice and note that the documentation was built using MkDocs,  on the footer, following
the model of mkdocs theme

Add copyright footer to base.html

---

mkdocs/config.py
mkdocs/test.py

Don't use the default theme if the user only specifies a theme_dir

---

mkdocs/build.py
mkdocs/themes/mkdocs/base.html
mkdocs/themes/readthedocs/base.html

Add build date and MkDocs version to the output

---

README.md
docs/index.md
docs/user-guide/styling-your-docs.md

- Remvoed a false promise from the home page
- Linked to the mailing list
- Fixed a broken screenshot link

Some minor docs updates

---

.travis.sh
mkdocs/config.py
mkdocs/tests/config_tests.py

Don't allow the docs_dir to be witin the site_dir

---

mkdocs/serve.py

Only watch directories that exist

---

mkdocs/tests/nav_tests.py
mkdocs/themes/readthedocs/breadcrumbs.html

Add a test to verify ancestors and add RTD breadcrumbs

---

mkdocs/build.py

This can be used with `mkdocs build --verbose`. It doesn't add a ton of
output, but if we get an error it will give us an idea on what page it
happens.

Add some basic debug logging to show what the build is doing

---

mkdocs/themes/amelia/css/base.css
mkdocs/themes/amelia/js/base.js
mkdocs/themes/bootstrap/css/base.css
mkdocs/themes/bootstrap/js/base.js
mkdocs/themes/cerulean/css/base.css
mkdocs/themes/cerulean/js/base.js
mkdocs/themes/cosmo/css/base.css
mkdocs/themes/cosmo/js/base.js
mkdocs/themes/cyborg/css/base.css
mkdocs/themes/cyborg/js/base.js
mkdocs/themes/flatly/css/base.css
mkdocs/themes/flatly/js/base.js
mkdocs/themes/journal/css/base.css
mkdocs/themes/journal/js/base.js
mkdocs/themes/mkdocs/css/base.css
mkdocs/themes/mkdocs/js/base.js
mkdocs/themes/readable/css/base.css
mkdocs/themes/readable/js/base.js
mkdocs/themes/simplex/css/base.css
mkdocs/themes/simplex/js/base.js
mkdocs/themes/slate/css/base.css
mkdocs/themes/slate/js/base.js
mkdocs/themes/spacelab/css/base.css
mkdocs/themes/spacelab/js/base.js
mkdocs/themes/united/css/base.css
mkdocs/themes/united/js/base.js
mkdocs/themes/yeti/css/base.css
mkdocs/themes/yeti/js/base.js

Consistent behaviour on page load and anchor click now.
Using the :before css to insert a margin above the item being linked.

Fixing the scroll to anchor tags

---

mkdocs/themes/amelia/js/base.js
mkdocs/themes/bootstrap/js/base.js
mkdocs/themes/cerulean/js/base.js
mkdocs/themes/cosmo/js/base.js
mkdocs/themes/cyborg/js/base.js
mkdocs/themes/flatly/js/base.js
mkdocs/themes/journal/js/base.js
mkdocs/themes/mkdocs/js/base.js
mkdocs/themes/readable/js/base.js
mkdocs/themes/simplex/js/base.js
mkdocs/themes/slate/js/base.js
mkdocs/themes/spacelab/js/base.js
mkdocs/themes/united/js/base.js
mkdocs/themes/yeti/js/base.js

Added table-striped and table-hover classes to tables

Adding nicer css classes to tables

---

mkdocs/config.py

Fixing error when assigning config file 

---

mkdocs/new.py

Don't overwrite index.md files with `mkdocs new`

---

mkdocs/gh_deploy.py

Add an option to specify the branch when deploying to GitHub

---

mkdocs/utils.py

Don't delete hidden files or directories with --clean

---

mkdocs/themes/readthedocs/base.html

Add favicon to the RTD theme

---

mkdocs/main.py
mkdocs/new.py
mkdocs/tests/new_tests.py

Fix a Unicode Issue with `mkdocs new`

---

mkdocs/new.py

Improved 92c66ee witn unicode literals.

---

mkdocs/config.py
mkdocs/serve.py
requirements.txt
setup.py

Use python-livereload to automatically refresh your browser.
Closes #163

Automatically refresh the browser on edits

---

docs/user-guide/configuration.md

Adds some description on the strict parameter

Add strict parameter to docs

---

mkdocs/nav.py
mkdocs/tests/nav_tests.py

Fix an issue with no child titles

---

docs/index.md
docs/user-guide/configuration.md
docs/user-guide/writing-your-docs.md

This change explicitly calls out how to do multi-level documentation.
Closes #475

Add further documentation about the pages config

---

mkdocs/cli.py
mkdocs/config.py
mkdocs/tests/config_tests.py

Fixed a couple of Typos in the recent CLI refactor

---

mkdocs/build.py
mkdocs/cli.py

This is based on #450 - so the diff here shows way too much.

Start the deprecation of the json cmd

---

mkdocs.yml
mkdocs/config.py
mkdocs/nav.py
mkdocs/tests/utils_tests.py
mkdocs/utils.py

Update auto pages configuration under the new nested Navigation structure

---

docs/user-guide/configuration.md

BTW: I would like to autogenerate `mkdocs.yml` for a [julia documentation package](https://github.com/peter1000/Lexicon.jl) and wanted to ask if you mind if I quite closely reuse your configuration names and describtion?
I saw there the typo.
Thanks
P

Fixes typo

---

mkdocs/build.py
mkdocs/cli.py
mkdocs/gh_deploy.py
mkdocs/new.py

This is an effort towards making the output more consistent.

Use log.info where possible and improve log formatting.

---

mkdocs/cli.py
mkdocs/serve.py
mkdocs/tests/integration.py
requirements/project.txt
setup.py

Make auto-reloading optional

---

tox.ini

We need to pass through LANG for encoding to work.
Fixes #524

As of Tox 2.0 the environment is far more limited

---

docs/about/contributing.md

Add a note about installing the dev version

---

docs/user-guide/writing-your-docs.md

remove lorem ipsum

---

docs/user-guide/writing-your-docs.md

remove more lorem ipsum

---

docs/user-guide/configuration.md

Document `extra_templates`

---

.travis.yml
setup.py

Don't use Travis for deploying

---

docs/about/release-notes.md
mkdocs.yml
mkdocs/cli.py
mkdocs/themes/readthedocs/base.html

Add site_author and site_description to the ReadTheDocs theme

---

mkdocs/themes/readthedocs/css/theme_extra.css

Improve the inline code block style within admonitions in the RTD theme

---

mkdocs/config/config_options.py
mkdocs/tests/config/config_options_tests.py

Ignore invalid symlinks

---

docs/about/release-notes.md
mkdocs/__init__.py

Start the deprecation of Python 2.6 support

---

mkdocs/config/base.py
mkdocs/config/config_options.py

Reset the warnings on a config option when they are logged

---

docs/about/release-notes.md
mkdocs/themes/mkdocs/css/base.css

Scroll the TOC when it becomes too long.

---

docs/about/release-notes.md
mkdocs/nav.py
mkdocs/tests/nav_tests.py

Add all ancestors to a page

---

docs/about/release-notes.md
mkdocs/nav.py
mkdocs/tests/nav_tests.py
mkdocs/utils/__init__.py

Copy HTML files again

---

docs/index.md

Confused me when I was reading through.

docs/index.md: doc_dir default is "docs" not "doc"

---

mkdocs/themes/readthedocs/base.html

Fix for #785 to have a proper display on IE of readthedocs theme

Added html meta X-UA-Compatible to properly display pages in IE

---

docs/about/release-notes.md

This should address #796. I didn't include every little change, but anything of note should be there.

Update release notes

---

requirements/project-min.txt
requirements/project.txt
setup.py

Lower required Click version

---

docs/about/contributing.md

Minor typo

---

docs/about/release-notes.md
mkdocs/config/config_options.py

Only display the warning for a specific set of themes

---

mkdocs/commands/serve.py

fix issue #822

---

docs/about/release-notes.md
mkdocs/__init__.py
mkdocs/config/config_options.py

Handle relative paths in symlinks

---

docs/index.md

Proposed changes to index.md related to mkdocs #818 & #824

Proposed changes to index.md related to mkdocs #818 & #824

---

docs/about/release-notes.md
mkdocs/__main__.py
mkdocs/commands/serve.py

This adds a flag to specify the `theme_dir` from the command line.

Add flag to add theme_dir from command line

---

docs/about/release-notes.md
mkdocs/commands/build.py
mkdocs/themes/readthedocs/base.html
mkdocs/utils/filters.py

Convert context to JSON when it is being passed to JavaScript

---

.travis.yml
docs/index.md

Closes #666 as the outstanding issue with the linter has been resolved.

Enforce markdownlint test.

---

docs/user-guide/writing-your-docs.md

Fix Markdown table syntax

---

MANIFEST.in

Include .woff2 font files in build.

---

mkdocs/utils/ghp_import.py

Fixes #722. See also davisp/ghp-import#52

Decode revision for update-ref call.

---

docs/about/release-notes.md

This addresses the various fixes I pushed recently. I need to do a better job remembering to include these in each fix.

Update 0.16 release notes to include recent changes.

---

docs/user-guide/configuration.md
docs/user-guide/custom-themes.md
docs/user-guide/styling-your-docs.md

I think this separates the differences between custom themes and customizing an existing theme properly. Any and all feedback is welcome.

Document theme_dir. Fixes #863

---

mkdocs/themes/mkdocs/js/base.js

Manually set the correct highlighted TOC item when the user clicks it

---

docs/about/release-notes.md
mkdocs/utils/__init__.py

Follow links when copying media files.

---

mkdocs/commands/build.py

Avoid logging duplicate messages.

---

docs/about/release-notes.md
mkdocs.yml

We never explicitly listed people before, this should make it
clearer who is behind the project.
Fixes #950

Add a note about the MkDocs team members.

---

docs/user-guide/deploying-your-docs.md

Add a note about 404 pages on the deploying page

---

mkdocs/themes/mkdocs/nav-sub.html

Remove the link from parent options in the navigation

---

docs/user-guide/configuration.md
docs/user-guide/writing-your-docs.md

Fixes #992. Not sure how this was missed.

Document `pages` config setting default behavior.

---

mkdocs/nav.py

Acknowledge SOURCE_DATE_EPOCH on individual pages.

---

mkdocs/__main__.py
mkdocs/tests/cli_tests.py

Improve CLI Tests

---

docs/index.md

Added a section covering package managers and some more notes
about Windows (specificly about adding Python to the PATH).
Fixes #932.

Added some system specific installation instructions.

---

docs/user-guide/configuration.md

Clean up configuration.md links.

---

docs/index.md

Remove a link which was added twice to the markdown file

Remove link added twice

---

mkdocs/themes/mkdocs/js/base.js

Ensure scrollspy behavior does not affect nav bar.

---

mkdocs/commands/serve.py

Fix for https://github.com/mkdocs/mkdocs/issues/1040

[ISSUE 1040] The dev server doesn't serve template provided error pages

---

requirements/test.txt

Remove more PY26 specific code.

---

docs/user-guide/custom-themes.md

custom-themes.md: fix a homepage typo

---

.travis.yml
appveyor.yml
tox.ini

Adds support for Python 3.6

---

mkdocs/config/config_options.py
mkdocs/contrib/legacy_search/__init__.py
mkdocs/plugins.py

these are several changes regarding the plugin code that were necessary or i found useful when i wrote a plugin.

Enhancements concerning plugins

---

appveyor.yml
tox.ini

Update appveyor config.

---

docs/about/release-notes.md

Now up-to-date with current commits.

Update release notes.

---

docs/user-guide/plugins.md

Fix typo with plugins module name

---

docs/user-guide/writing-your-docs.md
mdl_ruleset.rb

Present the sections in a logical manner:
1. File Layout (where to save documents)
* Configure Navigation...
2. Writing with Markdown
* Supported extensions...
Added documentation for all included extensions. Also added some basic
information about Markdown; pointing to the implementation and rules.
Fixes #1385.

Refactor writing-your-docs.md

---

mkdocs/themes/mkdocs/css/base.css

Attempt at addressing #1394 
I can't test it myself on a big screen, could @rpkilby or others test if it indeed solves the problem?

Avoid `background-attachment: fixed` for better performance

---

mkdocs/themes/mkdocs/base.html
mkdocs/themes/readthedocs/base.html

Is faster, safer and the recommended method by Google.

Always load Google Analytics over HTTPS

---

mkdocs/themes/mkdocs/base.html

Polyfill for media queries.
REF: https://github.com/scottjehl/Respond/releases

Update RespondJS to latest version

---

mkdocs/commands/build.py

A small patch to introduce compressed sitemap.xml.gz

Enable compressed sitemap.xml

---

docs/user-guide/plugins.md

Better document plugin config

---

.travis.yml
appveyor.yml
docs/about/release-notes.md
docs/index.md
requirements/project.txt
setup.py
tox.ini

Also up tornado version to >=5.0. Fixes #1427.

Drop official support for Python 3.3.

---

docs/user-guide/deploying-your-docs.md

Fixes #1291 and made possable by the work in #1376.

Document deploying to GH User/Org Pages.

---

docs/about/release-notes.md
mkdocs/templates/sitemap.xml

Add multi-level nesting support to sitemap.xml

---

docs/user-guide/deploying-your-docs.md

Document using custom domains with GitHub Pages.

---

docs/user-guide/styling-your-docs.md

Document the builtin themes' lack of support for multi-level nav.

---

docs/about/release-notes.md
mkdocs/themes/mkdocs/js/base.js

Close search modal when result is selected.

---

docs/user-guide/styling-your-docs.md

See rtfd/readthedocs.org#3438.
Or maybe we should include a screenshot in this repository, to be independent of possible future changes?

docs: Replace screen_mobile.png reference with a working one.

---

mkdocs/tests/utils/utils_tests.py
mkdocs/utils/__init__.py

These were some orphan remnants from the pages refactor.

Remove some unused code.

---

mkdocs/__init__.py

Alpha 1 of version 1.0.
Version 1.0 is a big deal as we are promising backward compatibility moving forward. And we made a lot of changes for this release. Therefore, I'm being cautious with the release. Alpha now, then a beta, a release candidate, and then the final release. I'm guessing a week or two between each.

Up version to 1.0a1

---

mkdocs/themes/mkdocs/base.html

HTTPS link to MkDocs site
Always load highlight.js over HTTPS

HTTPS links

---

mkdocs/structure/nav.py

Use DEBUG log level for external links in nav.

---

mkdocs/__init__.py

If there are no changes over the next week, this will become 1.0 Final in a week. If we have any changes within the next week, then 1.0rc2 will be released next week.

Up version to 1.0rc1

---

docs/user-guide/writing-your-docs.md
mkdocs/structure/files.py
mkdocs/tests/structure/file_tests.py

Exclude README.md if index.md is present.

---

mkdocs/commands/build.py
mkdocs/contrib/search/templates/search/main.js
mkdocs/tests/build_tests.py

Fix base_url in error pages.

---

mkdocs/tests/theme_tests.py
mkdocs/theme.py

handle existing but empty mkdocs_theme.yml files correctly

---

docs/user-guide/custom-themes.md

Remove reference to now deprecated template vars

---

docs/index.md

fix `pages` in `nav`
pages is deprecated

pages is deprecated

---

docs/about/release-notes.md
mkdocs/themes/readthedocs/base.html

Add canonical tag to readthedocs theme

---

docs/about/release-notes.md
mkdocs/structure/files.py
mkdocs/tests/structure/file_tests.py

Ensure theme files do not override docs_dir files

---

mkdocs/structure/files.py

My naive proposal on solution for #1694

logging if index.md and readme.md are located in same folder #1694

---

docs/index.md

Add more specific installation requirements when installing manually via python and pip for version 1.0.0+

Update installation requirements

---

mkdocs/themes/readthedocs/base.html

Fixes "is home page" check when rendering title

---

mkdocs/themes/mkdocs/search-modal.html

This fixes my own comment from #1718.

Fix aria-labelledby value for #mkdocs_search_modal

---

docs/about/release-notes.md
mkdocs/templates/sitemap.xml

Fixes Issue #1742 by not creating sitemap.xml entries for external links

skip external links in nav in sitemap

---

docs/about/release-notes.md
mkdocs/structure/files.py
mkdocs/tests/structure/file_tests.py

Exclude Markdown files and READMEs from theme.

---

docs/about/release-notes.md
mkdocs/config/config_options.py

Properly build `ValidationError` message for `custom_dir`.

---

.gitignore
mkdocs/commands/new.py
mkdocs/tests/integration/unicode/docs/Übersicht.md

When generating a new site documentation, "mkdocs -h" is suggested to fix issue #1859

When generating a new site documentation, "mkdocs -h" is suggested to fix issue #1859

---

docs/about/release-notes.md
mkdocs/commands/gh_deploy.py

Properly identify deployment version

---

mkdocs/commands/gh_deploy.py
mkdocs/tests/gh_deploy_tests.py

fix minor typo

---

docs/about/release-notes.md
mkdocs/structure/files.py

Ensure theme files do not override docs_dir files on Windows

---

docs/user-guide/writing-your-docs.md

Also added a few additional clarifications about how MkDocs handles files in the docs_dir.
Fixes #1924.

Document that dot files are ignored.

---

.travis.yml
appveyor.yml
docs/about/release-notes.md
setup.py
tox.ini

Python dropped support for 3.4 months ago.

Drop Python 3.4 and add Python 3.8.

---

docs/about/release-notes.md

Updated Release notes to reflect the changes by the bootstrap update. #1897

Updated release notes for 1.1

---

docs/about/release-notes.md
mkdocs/contrib/search/templates/search/lunr.js

Not much to say here. I did a quick manual test and everything appears to be working. The diff is pretty big, but it's mostly whitespace changes.

Update to lunr.js 2.3.8

---

mkdocs/commands/serve.py

Fix simple typo: seperate -> separate

---

docs/about/release-notes.md
mkdocs/structure/pages.py
mkdocs/tests/structure/page_tests.py

Ignore links which start with a backslash.

---

docs/about/release-notes.md
mkdocs/__init__.py
mkdocs/config/config_options.py
mkdocs/plugins.py

Also fixed a couple flake8 issues caught by the latest update.

Bump version to 1.1.1

---

docs/user-guide/writing-your-docs.md

Fixing a broken internal anchor link in the docs

---

mkdocs/config/config_options.py
mkdocs/utils/__init__.py

This PR is just a minor simplification for improved readability.

Prefer list comprehensions over list.append()

---

setup.py

Add the trove classifier: `Programming Language :: Python :: 3.8`

Add trove classifier for Python 3.8

---

docs/index.md

Wonderful starter guide, absolutely spot on, thank you! Please permit me to offer this minor typo fix. Thanks.

Make clear the distinction between and use of `docs_dir` and `docs`

---

docs/user-guide/custom-themes.md

Easy navigation and easy reading for others

Fix broken url in docs

---

mkdocs/utils/__init__.py

I have profiled a doc site that I have (with **326 pages**) and got its build time (under profiler) from ~**27**s to ~**24**s. It also has an outsized benefit on repeated `serve` builds.
I split up the `normalize_url` function, investigated in detail which parts of it benefit from caching (also from unlimited vs limited cache size) and configured it accordingly.
<table><tr><th>Before</th><th>After</th></tr><tr><td>
</td><td>
</td></tr></table>

Cache results of normalize_url for a performance boost

---

README.md
docs/index.md

Updates links from the groups to the new discussions section.
Closes #2256

Link to GitHub discussions

---

README.md
setup.py

Improves readme with a different structure and some link changes.
The landscape.io links have been removed as this project seems discontinued since April 2020

Redesign Readme

---

mkdocs/plugins.py
mkdocs/tests/plugin_tests.py
mkdocs/tests/utils/utils_tests.py
mkdocs/utils/__init__.py
requirements/project-min.txt
requirements/project.txt
setup.py

Replace pkg_resources with importlib_metadata

---

mkdocs/commands/gh_deploy.py
requirements/project-min.txt
requirements/project.txt
setup.py

This removes the final dependency on pkg_resources. Closes #2347.

Replace pgk_resources.parse_version with packaging.version.parse

---

docs/about/release-notes.md
docs/dev-guide/themes.md

Correct docs of `page` template context var

---

docs/about/release-notes.md
mkdocs/contrib/search/templates/search/lunr.js
setup.py

Closes #2306. Please let me know if any other changes are needed!

Update lunr and lunr.js to 0.5.9 and 2.3.9

---

docs/about/release-notes.md
mkdocs/structure/pages.py
mkdocs/tests/structure/nav_tests.py

Identify homepage when use_directory_urls is False

---

LICENSE
README.md

Added License section to the bottom of the README and update the copyright year and add "-present" to it in order to keep the license updated with the ongoing year.

Update the LICENSE and the README

---

docs/about/release-notes.md
docs/user-guide/configuration.md
mkdocs/contrib/search/__init__.py
mkdocs/contrib/search/search_index.py
mkdocs/tests/search_tests.py
setup.py

See discussion in yeraydiazdiaz/lunr.py#94 for details.

Remove hard dependency on lunr.py

---

docs/about/release-notes.md
docs/getting-started.md
docs/user-guide/configuration.md
docs/user-guide/deploying-your-docs.md

Clean up and improve the documentation following some recent changes.
Specificaly, ensure we consistantly document *two* required settings.

Documentation improvements

---

docs/about/release-notes.md
docs/user-guide/configuration.md
mkdocs/config/base.py
mkdocs/config/config_options.py
mkdocs/tests/config/config_options_tests.py
mkdocs/tests/plugin_tests.py
mkdocs/tests/utils/utils_tests.py
mkdocs/utils/__init__.py
requirements/project-min.txt
requirements/project.txt
setup.py

This implements the proposal in [this comment](https://github.com/mkdocs/mkdocs/issues/2218#issuecomment-843488261) of #2218.

Add support for Configuration Inheritance

---

docs/about/release-notes.md
mkdocs/__init__.py

I believe we are ready to release version 1.2. Thanks to everyone who contributed. There is a lot of long-desired stuff in this release.

Bump version to 1.2

---

docs/user-guide/choosing-your-theme.md

https://github.com/mkdocs/mkdocs/issues/2509

Don't announce support of zh_CN locale yet, as there's a bug

---

docs/about/contributing.md

- Replace Travis link by Github Actions one.
- Fix jinja2 i18n extension link.

Fix contribution guide links

---

README.md
docs/user-guide/configuration.md
mkdocs/config/config_options.py
mkdocs/tests/structure/page_tests.py
mkdocs/themes/readthedocs/css/theme_extra.css

Found using [codespell](https://github.com/codespell-project/codespell).

Fix various typos

---

docs/dev-guide/plugins.md

Fix old Jinja Environment link.

Fix Jinja Environment link

---

mkdocs/themes/readthedocs/locales/zh_CN/LC_MESSAGES/messages.po

The translation was synchronized with the latest messages.pot

zh_CN: Update the translation of readthedocs

---

mkdocs/themes/readthedocs/locales/es/LC_MESSAGES/messages.po

Update Spanish translation for Readthedocs theme

---

.gitignore
mkdocs/themes/readthedocs/locales/pt_BR/LC_MESSAGES/messages.po

Update brazilian portuguese translation for readthedocs Theme

---

mkdocs/themes/readthedocs/locales/ja/LC_MESSAGES/messages.po

The issue:
- #2695
@oprypin Thanks!

Update ja translation for readthedocs theme.

---

docs/about/release-notes.md

Currently errors clicking the link

chore: fix relative link

---

mkdocs/utils/filters.py

Fixes #2794﻿
Fixes #2799
Closes #2795

Compatibility with Jinja2 3.1.0

---

docs/dev-guide/themes.md

dev-guide: document page.file

---

mkdocs/contrib/search/templates/search/main.js

Prevent XSS searching in builtin themes

---

docs/user-guide/configuration.md

Fix typo in configuration.md

---

docs/about/contributing.md
docs/dev-guide/themes.md
mkdocs/__main__.py
mkdocs/themes/mkdocs/css/base.css
mkdocs/themes/readthedocs/base.html
mkdocs/themes/readthedocs/css/theme_extra.css
tox.ini

- Use `GitHub` in correct case
- Change `{% if foo%}` to `{% if foo %}`
- Convert tabs to spaces
- Change a few 2 or 3 spaces indent to 4 spaces

Clean up some code

---

mkdocs/themes/mkdocs/locales/it/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/it/LC_MESSAGES/messages.po

I made a quick translation for both the themes.

Italian translation for mkdocs and readthedocs themes

---

mkdocs/tests/search_tests.py

Everything after an `and` was never run because `None and anything` short-circuits to `None`.
And if it *did* run, it would've failed

Fix and refactor a convoluted test

---

mkdocs/structure/pages.py
mkdocs/tests/structure/page_tests.py
mkdocs/themes/mkdocs/base.html
mkdocs/themes/mkdocs/locales/de/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/es/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/fa/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/fr/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/it/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/ja/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/pt_BR/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/zh_CN/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/messages.pot
mkdocs/themes/readthedocs/breadcrumbs.html
mkdocs/themes/readthedocs/locales/de/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/es/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/fa/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/fr/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/it/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/ja/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/pt_BR/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/zh_CN/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/messages.pot

ref https://github.com/mkdocs/mkdocs/pull/1874#issuecomment-1214161618

Allow an empty `repo_url` when still specifying a `edit_uri`

---

.github/workflows/tox.yml
mkdocs/tests/integration.py
requirements/lint.txt
requirements/project-min.txt
requirements/project.txt
requirements/test.txt
setup.py
tox.ini

And install npm dependencies automatically / on the fly

Synchronize requirements files, reduce deps installation for lint

---

mkdocs/themes/mkdocs/locales/zh_CN/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/zh_CN/LC_MESSAGES/messages.po

mkdocs item: Edit 翻译 — 中文（中国）: 编辑, ID: 6
readthedocs item:Edit 翻译 — 中文（中国）: 编辑, ID: 7

zh_CN: Update translations of mkdocs and readthedocs themes

---

mkdocs/config/base.py
mkdocs/config/config_options.py
mkdocs/config/defaults.py
mkdocs/contrib/search/__init__.py
mkdocs/plugins.py
mkdocs/tests/config/config_options_tests.py
mkdocs/tests/config/config_tests.py
mkdocs/tests/plugin_tests.py

Please review commit-by-commit.

Refactor ConfigOptions

---

.github/workflows/tox.yml
mkdocs/commands/build.py
mkdocs/commands/new.py
mkdocs/config/base.py
mkdocs/config/defaults.py
mkdocs/contrib/search/__init__.py
mkdocs/contrib/search/search_index.py
mkdocs/exceptions.py
mkdocs/livereload/__init__.py
mkdocs/localization.py
mkdocs/plugins.py
mkdocs/structure/files.py
mkdocs/structure/nav.py
mkdocs/structure/pages.py
mkdocs/structure/toc.py
mkdocs/theme.py
mkdocs/utils/__init__.py
mkdocs/utils/filters.py
mkdocs/utils/meta.py
requirements/lint.txt
setup.cfg
tox.ini

(including some behavior changes, assumed to be no-op)
This is based on auto-generated annotations from "monkeytype".

Add a lot more type annotations, fix new type warnings

---

docs/dev-guide/plugins.md
docs/img/plugin-events.py
docs/img/plugin-events.svg
mkdocs/__main__.py
mkdocs/commands/build.py
mkdocs/commands/serve.py
mkdocs/config/config_options.py
mkdocs/livereload/__init__.py
mkdocs/plugins.py
mkdocs/tests/plugin_tests.py
requirements/project-min.txt
requirements/project.txt
setup.py

"One-time events" `on_startup(command: str, dirty: bool)`, `on_shutdown`.
Their presence also shows that a plugin *wants* to persist across builds. Otherwise they will be re-created, to not change any existing behavior.
* Closes #2971
* Closes #2600

Add plugin events that persist across builds in `mkdocs serve`

---

requirements/project-min.txt
requirements/project.txt
setup.py

Actually depend on 'colorama' on Windows

---

mkdocs/livereload/__init__.py
mkdocs/structure/files.py
mkdocs/structure/pages.py
mkdocs/tests/structure/file_tests.py
mkdocs/tests/structure/page_tests.py

Relative links end with slash even for homepage links

---

docs/user-guide/choosing-your-theme.md
mkdocs/themes/mkdocs/locales/nb/LC_MESSAGES/messages.po
mkdocs/themes/mkdocs/locales/nn/LC_MESSAGES/messages.po

I also reordered the locale list alphabetically (except for English).

Translate mkdocs theme to Norwegian (nb and nn)

---

docs/user-guide/deploying-your-docs.md

Per our discussion on https://gitter.im/mkdocs/community?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications regarding untracked files and uncommitted changes being unexpectedly included in the pages as deployed.

Add warning for untracked files, uncommitted changes.

---

docs/user-guide/configuration.md

Align edit_url text and example

---

mkdocs.yml

Changes:
- themes/footer: fix twitter link changed from https://twitter.com/_tomchristie to https://twitter.com/tomchristie

themes/footer: fix twitter link

---

docs/user-guide/choosing-your-theme.md
mkdocs/themes/mkdocs/locales/id/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/id/LC_MESSAGES/messages.po

Add translations for Bahasa Indonesia.

add id (Indonesian) translations

---

docs/about/contributing.md
docs/dev-guide/translations.md
docs/user-guide/choosing-your-theme.md
mkdocs/themes/mkdocs/locales/tr/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/tr/LC_MESSAGES/messages.po

* From https://github.com/mkdocs/mkdocs/discussions/3194
* From https://github.com/mkdocs/mkdocs/pull/2946
@mss1451 - does this look ok?

Generalize `tr_TR` translations to just `tr`, explain how to decide this

---

mkdocs/structure/files.py
mkdocs/tests/structure/file_tests.py

+ Cache the value of `documentation_pages`

Allow to set a different `dest_uri` when creating a `File`

---

mkdocs/config/config_options.py
mkdocs/config/defaults.py
mkdocs/tests/config/config_options_tests.py

* https://github.com/mkdocs/mkdocs/discussions/3226

Clarify that `Private` config can be accessed, add a type to `mdx_configs`

---

docs/about/contributing.md

As always, feel free to change the phrasing. I'm not the best at English sentences :slightly_smiling_face:

Add note about formatting code

---

docs/dev-guide/plugins.md
mkdocs/plugins.py

As discussed in https://github.com/mkdocs/mkdocs/discussions/3241.
Not sure if tests are needed, the code is quite trivial.

Add plugin logger

---

mkdocs/commands/build.py
mkdocs/commands/serve.py
mkdocs/config/base.py
mkdocs/exceptions.py
mkdocs/livereload/__init__.py
mkdocs/tests/livereload_tests.py

Don't abort `mkdocs serve` for build errors during rebuilds

---

mkdocs/__main__.py

* These disable it: `--no-color` flag, `NOCOLOR=` var, or `| cat`.
* This force-enables it: `--color`
---
* Closes #2862

Make colorful/indented output optional, decrease indent

---

docs/about/release-notes.md
docs/getting-started.md
mkdocs/__init__.py

Preview: https://github.com/mkdocs/mkdocs/blob/relnotes/docs/about/release-notes.md#version-150-2023-07-19

Release notes for 1.5.0

---

mkdocs/__main__.py
mkdocs/commands/serve.py
mkdocs/livereload/__init__.py
mkdocs/tests/cli_tests.py

and nearby refactor
* Fixes #3319

Restore functionality of `--no-livereload`

---

mkdocs/structure/pages.py

Fixes https://github.com/pdm-project/pdm/issues/2152

Correct detection of dropping anchorlink from page title

---

mkdocs/contrib/search/lunr-language/lunr.ar.js
mkdocs/contrib/search/lunr-language/lunr.hi.js
mkdocs/contrib/search/lunr-language/lunr.hy.js
mkdocs/contrib/search/lunr-language/lunr.kn.js
mkdocs/contrib/search/lunr-language/lunr.ko.js
mkdocs/contrib/search/lunr-language/lunr.ro.js
mkdocs/contrib/search/lunr-language/lunr.ru.js
mkdocs/contrib/search/lunr-language/lunr.sa.js
mkdocs/contrib/search/lunr-language/lunr.ta.js
mkdocs/contrib/search/lunr-language/lunr.te.js
mkdocs/contrib/search/lunr-language/lunr.zh.js
mkdocs/tests/search_tests.py

Bump from 1.4.0 to 1.12.0
This adds support for:
- hi
- hy
- kn
- ko
- sa
- ta
- te
- zh

Add new supported languages by updating lunr-languages to 1.12.0

---

.flake8
.github/workflows/ci.yml
docs/hooks.py
mkdocs/commands/build.py
mkdocs/commands/get_deps.py
mkdocs/config/config_options.py
mkdocs/config/defaults.py
mkdocs/contrib/search/__init__.py
mkdocs/livereload/__init__.py
mkdocs/localization.py
mkdocs/plugins.py
mkdocs/structure/files.py
mkdocs/structure/pages.py
mkdocs/tests/config/config_tests.py
mkdocs/tests/livereload_tests.py
mkdocs/tests/structure/file_tests.py
mkdocs/tests/structure/page_tests.py
mkdocs/utils/__init__.py
mkdocs/utils/filters.py
pyproject.toml

Switch to "ruff" linter, enable many of its rules

---

mkdocs/structure/nav.py

unless the page value is a *strict* subclass of Page
* Addresses https://github.com/mkdocs/mkdocs/pull/3367#issuecomment-1710729408
@squidfunk @ultrabug

Keep the prior behavior of overwriting File.page

---

mkdocs/themes/mkdocs/locales/zh_TW/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/zh_TW/LC_MESSAGES/messages.po

Add zh_TW locale for built-in themes

---

mkdocs/livereload/__init__.py

Closes #3389. 
__Edit__: superseded by #3391.

Abort livereload request before navigation

---

.github/workflows/deploy-release.yml

https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
-no longer relies on any token

Change PyPI deploy to rely on "trusted publishers"

---

mkdocs/structure/pages.py
mkdocs/tests/build_tests.py

* If source page and destination page is excluded, cap log level to DEBUG
* If source page is excluded, cap log level to INFO
* Closes #3371

Reduce logs for invalid links if referring page is excluded

---

mkdocs/plugins.py
mkdocs/tests/plugin_tests.py

Warn when multiple 'on_page_read_source' handlers are added

---

pyproject.toml
requirements/requirements-docs.txt

Fix hatch environment 'docs' to use the local mkdocs checkout

---

pyproject.toml

I can't think of any other project that includes tests

Exclude tests from the wheel distribution

---

mkdocs/structure/pages.py

If it matches the priority of the 'toc' processor, it's more likely to be correct.
In particular, it enables us to see the inner headings that mkdocstrings creates.

Split out the anchor-collecting processor at an earlier priority

---

docs/user-guide/configuration.md
mkdocs/config/config_options.py

Also clean sys.path after the hook is done, for some semblance of isolation
Closes #3281

Add the hook file's directory to sys.path

---

mkdocs/themes/mkdocs/keyboard-modal.html
mkdocs/themes/mkdocs/search-modal.html

It became unstyled since the upgrade of Bootstrap
* Ref https://github.com/mkdocs/mkdocs/pull/3493#issuecomment-2060187664

Fix style of modal close button

---

mkdocs/tests/config/config_options_tests.py

Resolve CI

---

mkdocs/themes/mkdocs/js/base.js

Fixes https://github.com/mkdocs/mkdocs/issues/3691

Fix selector for dropdown

---

mkdocs/themes/mkdocs/locales/zh_CN/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/zh_CN/LC_MESSAGES/messages.po

I18N:Update Chinese (Simplified)

---

mkdocs/themes/mkdocs/js/base.js

Fixes https://github.com/mkdocs/mkdocs/issues/3728#issuecomment-2158727044.

Fix repeated clicks on menu leading to errors in console

---

docs/user-guide/deploying-your-docs.md

New link containing summary from GitHub.

Docs: Dead links at types of GitHub Pages sites.

---

docs/user-guide/configuration.md

Updated description of use_directory_urls

---

mkdocs/themes/mkdocs/js/base.js

Supersedes #3729 to fix #3728. I accidentally closed the PR by deleting my fork when cleaning up my repositories.

Fix prev/next keyboard navigation

---

mkdocs/themes/mkdocs/locales/nl/LC_MESSAGES/messages.po
mkdocs/themes/readthedocs/locales/nl/LC_MESSAGES/messages.po

Dutch translations added for the MkDocs and ReadTheDocs themes

Adding Dutch translations
